function examples = getexamples(~)
%GETEXAMPLES Get the examples.

%   Copyright 2011 The MathWorks, Inc.

examples ={{...
  'Design a highpass inverse sinc filter with a stopband',...
  '%           frequency of 0.35*pi rad/sample, and a passband frequency',...
  '%           of 0.45*pi rad/sample. Weight the passband to reduce ripple.',...
  'd = fdesign.isinchp(''N,Fst,Fp'',60,0.35,0.45);',...
  'Hd = design(d,''equiripple'',''Wpass'',10);',...
  'fvtool(Hd)'}};
% [EOF]
