function [RAPStat, AxHdl] = CreateRAPEmptyPlot(RAPStat, LayType)
%CreateRAPEmptyPlot    creates an empty RAP plot
%   AxHdl = CreateRAPEmptyAxis(RAPStat, LayoutType)
%
%   Attention! This function is an internal function belonging to the RAP 
%   project and should not be invoked from the MATLAB command prompt.

%B. Van de Sande 04-02-2004

TitleParam = RAPStat.PlotParam.Axis.Title;

%Create axis object ... 
[RAPStat, AxHdl] = CreateRAPAxis(RAPStat, LayType);
set(AxHdl, 'Box', 'on', 'Color', [1 0 0], 'Units', 'normalized', ...
    'YTick', [], 'YTickLabel', [], 'XTick', [], 'XTickLabel', []); %Red background color ...

%Create Text object ...
TxtHdl = text(0.5, 0.5, sprintf('No plot to be\ngenerated'));
set(TxtHdl, 'VerticalAlignment', 'middle', ...
             'HorizontalAlignment', 'center', ...
             'Color', TitleParam.Color, ...
             'FontName', TitleParam.FontName, ...
             'FontAngle', 'normal', ...
             'FontSize', CalcRAPFontSize(RAPStat, AxHdl, TitleParam.FontSize), ...
             'FontWeight', 'normal');