function P = uimenuProperties;
% uimenuProperties - all properties of uimenus in a cell array of strings

P = {    'Accelerator'    'BeingDeleted'    'BusyAction'    'ButtonDownFcn'    'Callback'    'Checked'    'Children'    'Clipping' ...
    'CreateFcn'    'DeleteFcn'    'Enable'    'ForegroundColor'    'HandleVisibility'    'HitTest'    'Interruptible'    'Label' ...
    'Parent'    'Position'    'Selected'    'SelectionHighlight'    'Separator'    'Tag'    'Type'    'UIContextMenu' ...
    'UserData'    'Visible'};
