%close all
%ui1=uicontrol('style','checkbox','string','Push me!','position',[20 20 80 20],...
%'value',1,'callback',['fprintf(''[Push me][%d]\n'',get(ui1,''value''))']);
%ui2=uicontrol('style','checkbox','string','Me too!','position',[120 20 80 20],...
%'callback',['fprintf(''[Me too][%d]\n'',get(ui2,''value''))']);

close all
ui1=uicontrol('style','text','string','Left text','position',[20 20 80 20],...
'HorizontalAlignment','left');
ui2=uicontrol('style','text','string','Center text','position',[120 20 80 20],...
'HorizontalAlignment','center');
ui3=uicontrol('style','text','string','Right text','position',[220 20 80 20],...
'HorizontalAlignment','right');