function examples = getexamples(~)
%GETEXAMPLES Get the examples.

%   Copyright 2011 The MathWorks, Inc.

examples ={{...
  'Design a minimum order highpass inverse sinc filter with a stopband',...
  '%           frequency of 0.75*pi rad/sample, and a passband frequency',...
  '%           of 0.85*pi rad/sample. Set the stopband attenuation to 75 dB',...
  '%           and the passband ripple to 0.1 dB.',...
  'd = fdesign.isinchp(''Fst,Fp,Ast,Ap'',.75,0.85,75,.1);',...
  'Hd = design(d,''equiripple'');',...
  'fvtool(Hd)'}};


% [EOF]
