function RGB = ColSym2RGB(ColSym)
%COLSYM2RGB converts color symbol to RGB vector
%   RGB = COLSYM2RGB(ColSym) converts the color symbol given by the character
%   string ColSym to a 3 element vector RGB.

%B. Van de Sande 11-03-2004

if (nargin ~= 1), error('Wrong number of input arguments.'); end
if ~ischar(ColSym) | (length(ColSym) > 1) | ~ismember(lower(ColSym), 'bgrcmyktw'), 
    error('First argument should be color symbol.'); 
end

switch lower(ColSym)
%Standard MATLAB color symbols ...
case 'b', RGB = [0 0 1]; %blue ...
case 'g', RGB = [0 1 0]; %green ...
case 'r', RGB = [1 0 0]; %red ...
case 'c', RGB = [0 1 1]; %cyan ...
case 'm', RGB = [1 0 1]; %magenta ...
case 'y', RGB = [1 1 0]; %yellow ...
case 'k', RGB = [0 0 0]; %black ...
%Extensions ...
case {'t', 'w'}, RGB = [1 1 1]; %white or transparant ...
end    