function examples = getexamples(~)
%GETEXAMPLES Get the examples.

%   Copyright 2011 The MathWorks, Inc.

examples = {{ ...
    'Design a bandstop Equiripple filter. Constrain the second passband to have ',...
    '%           a ripple of 0.5 dB.',...
    'h  = fdesign.bandstop(''N,Fp1,Fst1,Fst2,Fp2,C'',40,0.3,0.4,0.7,0.8);', ...
    'h.Passband2Constrained = true;',...
    'h.Apass2 = 0.5;',...
    'Hd = design(h, ''equiripple'');', ...
    '% Weight the stopbband to increase its attenuation.',...
    'Hd(2) = design(h, ''equiripple'', ''Wstop'', 10);'....  
    '% Compare the two designs.', ...
    'fvtool(Hd)'}};

% [EOF]
