function Template = EvalMove_getTemplate
Template.ds1.filename         = '';   %Name of datafile where MOV dataset is
                                      %  located
Template.ds1.icell            = NaN;  %Cell number of MOV dataset
Template.ds1.iseq             = NaN;  %Sequence number of MOV dataset
Template.ds1.seqid            = '';   %Identifier of MOV dataset
Template.dsntd.icell          = NaN;  %Cell number of noise NTD dataset
Template.dsntd.iseq           = NaN;  %Sequence number of noise NTD dataset
Template.dsntd.seqid          = '';   %Identifier of noise NTD dataset
Template.tag                  = 0;    %General purpose tag field
Template.createdby            = strtok(mfilename, '_'); %Name of MATLAB function
                                                        %that generated the data
Template.spkrate              = [];
Template.param.binmode        = '';   %Mode of binning
Template.param.binwidth       = NaN;  %Binwidth for histograms
Template.param.nbin           = NaN;  %Number of bins for histograms
Template.param.calcitdrng     = NaN;
Template.stim.type            = NaN;  %Type of stimulus (1, 2, 3 or 4)
Template.stim.nrep            = NaN;  %number of repetitions
Template.stim.noisetokenmaster= '';   %Information on noise token of master dss
Template.stim.noisetokenslave = '';   %Information on noise tokens of slave dss
Template.stim.spl             = NaN;  %Combined recording SPL
Template.stim.effspl          = NaN;  %Combined effective SPL
Template.stim.movedir         = NaN;  %Movement direction
Template.stim.itdbgn          = NaN;
Template.stim.itdend          = NaN;
Template.stim.effitdend       = NaN;
Template.stim.itdrate         = NaN;
Template.stim.effitdrate      = NaN;
Template.stim.delayslave      = NaN;
Template.hist.maxn            = NaN;
Template.hist.maxrate         = NaN;
Template.hist.bcatmax         = NaN;
Template.hist.minn            = NaN;
Template.hist.minrate         = NaN;
Template.hist.bcatmin         = NaN;
Template.hist.moddepth        = NaN;
Template.hist.bc              = NaN;
Template.hist.rate            = NaN;
Template.mov1.itdrate         = NaN;
Template.mov1.corrmax         = NaN;
Template.mov1.corrlagatmax    = NaN;
Template.mov1.latency         = NaN;
Template.mov1.ycpt            = NaN;
Template.mov3.dssi            = NaN;  %Dynamic Spatial Sensitivity Index(DSSI)
Template.mov3.bc              = NaN;
Template.mov3.dynn            = NaN;
Template.mov3.dynrate         = NaN;
Template.mov3.statn           = NaN;
Template.mov3.statrate        = NaN;
Template.thr.cf               = NaN;  %Characteristic frequency retrieved from
                                      %  threshold curve
Template.thr.sr               = NaN;  %Spontaneous rate retrieved from threshold
                                      %  curve
Template.thr.thr              = NaN;  %Threshold at characteristic frequency
Template.thr.q10              = NaN;  %Q10 retrieved from threshold curve
Template.thr.bw               = NaN;  %Width 10dB above threshold (Hz)
Template.RCN.Thr              = NaN;  %Data extracted from rate curve
Template.ntd.maxrate          = NaN;
Template.ntd.itdatmax         = NaN;
