function P = axesProperties;
% axesProperties - all properties of axes in a cell array of strings

P = {'ActivePositionProperty'    'ALim'    'ALimMode'    'AmbientLightColor'    'BeingDeleted'    'Box'    'BusyAction'  ...
    'ButtonDownFcn' ...
    'CameraPosition'    'CameraPositionMode'    'CameraTarget'    'CameraTargetMode'    'CameraUpVector'    'CameraUpVectorMode' ...
    'CameraViewAngle'    'CameraViewAngleMode'    'Children'    'CLim'    'CLimMode'    'Clipping'    'Color'    'ColorOrder' ...
    'CreateFcn'    'CurrentPoint'    'DataAspectRatio'    'DataAspectRatioMode'    'DeleteFcn'    'DrawMode'    'FontAngle' ...
    'FontName'    'FontSize'    'FontUnits'    'FontWeight'    'GridLineStyle'    'HandleVisibility'    'HitTest' ...
    'Interruptible'    'Layer'    'LineStyleOrder'    'LineWidth'    'MinorGridLineStyle'    'NextPlot'    'OuterPosition' ...
    'Parent'    'PlotBoxAspectRatio'    'PlotBoxAspectRatioMode'    'Position'    'Projection'    'Selected'    'SelectionHighlight'  ...
    'Tag' ...
    'TickDir'    'TickDirMode'    'TickLength'    'TightInset'    'Title'    'Type'    'UIContextMenu'    'Units'    'UserData' ...
    'View'    'Visible'    'XAxisLocation'    'XColor'    'XDir'    'XGrid'    'XLabel'    'XLim'    'XLimMode'    'XMinorGrid' ...
    'XMinorTick'    'XScale'    'XTick'    'XTickLabel'    'XTickLabelMode'    'XTickMode'    'YAxisLocation'    'YColor' ...
    'YDir'    'YGrid'    'YLabel'    'YLim'    'YLimMode'    'YMinorGrid'    'YMinorTick'    'YScale'    'YTick'    'YTickLabel' ...
    'YTickLabelMode'    'YTickMode'    'ZColor'    'ZDir'    'ZGrid'    'ZLabel'    'ZLim'    'ZLimMode'    'ZMinorGrid' ...
    'ZMinorTick'    'ZScale'    'ZTick'    'ZTickLabel'    'ZTickLabelMode'    'ZTickMode'};
