function P = figureProperties;
% figureProperties - all properties of figures in a cell array of strings

P = {    'Alphamap'    'BackingStore'    'BeingDeleted'    'BusyAction' ...
    'ButtonDownFcn'    'Children'    'Clipping'    'CloseRequestFcn' ...
    'Color'    'Colormap'    'CreateFcn'    'CurrentAxes' ...
    'CurrentCharacter'    'CurrentObject'    'CurrentPoint' ...
    'DeleteFcn'    'DockControls'    'DoubleBuffer'    'FileName' ...
    'FixedColors'    'HandleVisibility'    'HitTest'    'IntegerHandle' ...
    'Interruptible'    'InvertHardcopy'    'KeyPressFcn'    'KeyReleaseFcn' ...
    'MenuBar'    'MinColormap'    'Name'    'NextPlot'    'NumberTitle' ...
    'PaperOrientation'    'PaperPosition'    'PaperPositionMode'    'PaperSize' ...
    'PaperType'    'PaperUnits'    'Parent'    'Pointer'    'PointerShapeCData' ...
    'PointerShapeHotSpot'    'Position'    'Renderer'    'RendererMode' ...
    'Resize'    'ResizeFcn'    'Selected'    'SelectionHighlight' ...
    'SelectionType'    'ShareColors'    'Tag'    'ToolBar'    'Type' ...
    'UIContextMenu'    'Units'    'UserData'    'Visible'    'WindowButtonDownFcn' ...
    'WindowButtonMotionFcn'    'WindowButtonUpFcn'    'WindowScrollWheelFcn' ...
    'WindowStyle'    'WVisual'    'WVisualMode'};
