function P = uicontrolProperties;
% uicontrolProperties - all properties of uicontrols in a cell array of strings

P = {'BackgroundColor'    'BeingDeleted'    'BusyAction'    'ButtonDownFcn'    'Callback'    'CData'    'Children' ...
    'Clipping'    'CreateFcn'    'DeleteFcn'    'Enable'    'Extent'    'FontAngle'    'FontName'    'FontSize'    'FontUnits' ...
    'FontWeight'    'ForegroundColor'    'HandleVisibility'    'HitTest'    'HorizontalAlignment'    'Interruptible' ...
    'KeyPressFcn'    'ListboxTop'    'Max'    'Min'    'Parent'    'Position'    'Selected'    'SelectionHighlight' ...
    'SliderStep'    'String'    'Style'    'Tag'    'TooltipString'    'Type'    'UIContextMenu'    'Units'    'UserData' ...
    'Value'    'Visible'};
