function P = uipanelProperties;
% uipanelProperties - all properties of uipanels in a cell array of strings

P = {'BackgroundColor'  'BeingDeleted'  'BorderType' ...
    'BorderWidth'     'BusyAction'     'ButtonDownFcn'     'Children' ...
    'Clipping'     'CreateFcn'    'DeleteFcn'    'FontAngle' ...
    'FontName'     'FontSize'     'FontUnits'     'FontWeight' ...
    'ForegroundColor'     'HandleVisibility'     'HighlightColor' ...
    'HitTest'     'Interruptible'     'Parent'     'Position' ...
    'ResizeFcn'    'Selected'    'SelectionHighlight'    'ShadowColor' ...
    'Tag'    'Title'    'TitlePosition'    'Type'    'UIContextMenu' ...
    'Units'     'UserData'    'Visible'};

