function examples = getexamples(this)
%GETEXAMPLES   Get the examples.

%   Author(s): R. Losada
%   Copyright 2005 The MathWorks, Inc.

examples = {{ ...
    'Design a multistage Nyquist decimation filter.', ...
    'f = fdesign.decimator(16,''nyquist'',16,''TW,Ast'',.01,75); ',...
    'Hm = design(f,''multistage'');',...
    'info(Hm)'},...
    { ...
    'Repeat previous design using elliptic halfband filters.', ...
    'f = fdesign.decimator(16,''nyquist'',16,''TW,Ast'',.01,75); ',...
    'Hm = design(f,''multistage'',''HalfbandDesignMethod'',''ellip'');',...
    'info(Hm)'},...
     { ...
    'Repeat previous design using IIR linear phase halfband filters.', ...
    'f = fdesign.decimator(16,''nyquist'',16,''TW,Ast'',.01,75); ',...
    'Hm = design(f,''multistage'',''HalfbandDesignMethod'',''iirlinphase'');',...
    'info(Hm)'}};

% [EOF]
