function cm = DAdataStruct(SamP, filterIndex, bufSizes, bufReps, ...
   Nrepsil, Nplay, WarpDev, MaxSPL, createdby);

% DAdataStruct - fill DAdata structure
% i.e., data about D/A conversion that are common to all stimtypes
% Note: WarpDev is time-warp factor minus one (for display reasons).
if nargin<9, createdby = '??'; end;

cm = struct(...
   'samP',    SamP,...
   'filterIndex',filterIndex,...
   'bufSizes',bufSizes,...
   'bufReps', bufReps,...
   'bufDBNs', zeros(size(bufSizes)),...
   'Nrepsil', Nrepsil,...
   'Nplay',   Nplay,...
   'WarpDev', WarpDev, ...
   'MaxSPL',  MaxSPL, ...
   'createdby', createdby);
