function examples = getexamples(~)
%GETEXAMPLES Get the examples.

%   Copyright 2011 The MathWorks, Inc.

examples = {{ ...
    'Design a 80th order equiripple differentiator with a passband frequency of 0.4, ', ...
    '%           and a stopband attenuation of 40 dB.',...
    'h  = fdesign.differentiator(''N,Fp,Fst,Ast'',80,.4,.45,40);', ...
    'Hd = design(h, ''equiripple'', ''FilterStructure'', ''dfasymfir'');', ...
    'fvtool(Hd, ''MagnitudeDisplay'',''Magnitude'')'}};

% [EOF]

