function examples = getexamples(~)
%GETEXAMPLES Get the examples.

%   Copyright 2011 The MathWorks, Inc.

examples = {{ ...
    'Design a 50th order equiripple differentiator with a passband frequency of 0.4,', ...
    '%           and a passband ripple of 0.5 dB.',...
    'h  = fdesign.differentiator(''N,Fp,Fst,Ap'',50,.4,.45,0.5);', ...
    'Hd = design(h, ''equiripple'', ''FilterStructure'', ''dfasymfir'');', ...
    'fvtool(Hd, ''MagnitudeDisplay'',''Magnitude'')'}};

% [EOF]

