function hMainFigure = createSoundPressureUI()
% Function to create a UI to select the filter, the audio source and 
% display the rms pressure values before and after weighting.

%% Handles for UI objects and UDP sender.
% Declare and create all the UI objects in this interface here so that they
% can be used in any functions
hMainFigure     =   figure(...       % the main UI figure
                     'Name', 'Filter Tuning UI', ...
                     'MenuBar','none', ...
                     'Toolbar','none', ...
                     'NumberTitle','off', ...
                     'Color', get(0, 'defaultuicontrolbackgroundcolor'),...
                     'DeleteFcn', @hFigDeleteCallback);
                    
hMainText       =   uicontrol(...
                     'Style','text', ...
                     'Parent', hMainFigure, ...
                     'Units','normalized', ...
                     'Position', [0.15 0.80 0.70 0.2], ...
                     'String','Sound Pressure Measurement', ...
                     'FontUnits', 'normalized', ...
                     'FontSize', 0.3, ...
                     'FontWeight', 'bold');                      
                    
hStopSim        =   uicontrol(...    % button to stop the simulation  
                     'Parent', hMainFigure, ...
                     'Units','normalized', ...
                     'Position',[0.25 0.02 0.5 0.1], ...
                     'String','Stop Simulation', ...
                     'FontUnits', 'normalized', ...
                     'FontSize', 0.3, ...
                     'Callback', @hStopSimButtonCallback);  
                   
hFilterSelect   =   uicontrol(...   % pop up menu to select a filter
                     'Style', 'popup', ...                        
                     'Parent', hMainFigure, ...
                     'Units','normalized', ...
                     'Position', [0.25 0.38 0.5 0.1], ...
                     'String', {'None', ...
                         'A-Weighting', ...
                         'C-Weighting'}, ...
                     'FontUnits', 'normalized', ...
                     'FontSize', 0.3, ...
                     'Callback', @hFiltSelectCallback);
                    
hFilterText     =   uicontrol(...
                     'Style','text', ...
                     'Parent', hMainFigure, ...
                     'Units','normalized', ...
                     'Position', [0.25 0.48 0.5 0.1], ...
                     'String','Select a filter', ...
                     'FontUnits', 'normalized', ...
                     'FontSize', 0.3, ...
                     'FontWeight', 'bold');      
                    
hAudioSelect    =   uicontrol(...   % pop up menu to select an audio source
                     'Style', 'popup', ...                        
                     'Parent', hMainFigure, ...
                     'Units','normalized', ...
                     'Position', [0.25 0.68 0.5 0.1], ...
                     'String', {'White noise', ...
                        'External (mic)', ...
                        'Engine', ...
                        'Jet air plane', ...
                        'Turbine', ...
                        'Washing machine', ...
                        'Load file...'}, ...
                     'FontUnits', 'normalized', ...
                     'FontSize', 0.3, ...
                     'Callback', @hAudioSelectCallback);
                    
hAudioText      =   uicontrol(...
                     'Style','text', ...
                     'Parent', hMainFigure, ...
                     'Units','normalized', ...
                     'Position', [0.25 0.78 0.5 0.1], ...
                     'String','Select an audio source', ...
                     'FontUnits', 'normalized', ...
                     'FontSize', 0.3, ...
                     'FontWeight', 'bold');                       
                    
hAudioLoadedText =  uicontrol(...
                     'Style','text', ...
                     'Parent', hMainFigure, ...
                     'Units','normalized', ...
                     'Position', [0.25 0.58 0.5 0.1], ...
                     'String','White noise', ...
                     'FontUnits', 'normalized', ...
                     'FontSize', 0.3, ...
                     'Tag', 'StFileName');                     
                    
hLevelNoFiltText =  uicontrol(...
                     'Style','text', ...
                     'Parent', hMainFigure, ...
                     'Units','normalized', ...
                     'Position', [0.05 0.22 0.4 0.1], ...
                     'String','RMS pressure (dB) w/o weighting', ...
                     'FontUnits', 'normalized', ...
                     'FontSize', 0.3, ...
                     'FontWeight', 'bold');   
                    
hLevelFiltText  =   uicontrol(...
                     'Style','text', ...
                     'Parent', hMainFigure, ...
                     'Units','normalized', ...
                     'Position', [0.55 0.22 0.4 0.1], ...
                     'String','RMS pressure (dB) w/ weighting', ...
                     'FontUnits', 'normalized', ...
                     'FontSize', 0.3, ...
                     'FontWeight', 'bold');                      
                    
hLevelNoFiltValue = uicontrol(...
                     'Style','text', ...
                     'Parent', hMainFigure, ...
                     'Units','normalized', ...
                     'Position', [0.05 0.12 0.4 0.1], ...
                     'String', '0', ...
                     'FontUnits', 'normalized', ...
                     'FontSize', 0.3, ...
                     'Tag', 'StRmsPressureNoFilt');     
                    
hLevelFiltValue =   uicontrol(...
                     'Style','text', ...
                     'Parent', hMainFigure, ...
                     'Units','normalized', ...
                     'Position', [0.55 0.12 0.4 0.1], ...
                     'String', '0', ...
                     'FontUnits', 'normalized', ...
                     'FontSize', 0.3, ...
                     'Tag', 'StRmsPressureFilt');                     
                    
hUDP  = dsp.UDPSender;      % UDP sender
flagStopSim = false;        % Can be set to stop the simulation
filterNumber = 0;           % Can be changed to select a different filter
changeAudioFile = false;    % New audio source/file
audioSource = 0;            % Audio source ID
drawnow

%% Callback functions as nested functions
function sendUDP()
    packetUDP = zeros(1,4);
    % UDP packet contains filter value, audio source id, reset flag and 
    % stop simulation flag
    packetUDP(1) = flagStopSim;
    packetUDP(2) = filterNumber;
    packetUDP(3) = changeAudioFile;
    packetUDP(4) = audioSource;
    step(hUDP, packetUDP);
end

function hStopSimButtonCallback(~,~,~)
    % Called when "Stop Simulation" button is pressed
    flagStopSim = true;   
    sendUDP();
end

function hAudioSelectCallback(source,~)
    % Called when an audio source is selected from the pop-up menu
    str = get(source, 'String');
    val = get(source, 'Value');
    
    switch str{val}
        case 'External (mic)' 
            audioSource = 1;
            set(hAudioLoadedText, 'String', 'External source (mic)');
        case 'Engine'   
            audioSource = 2;
            set(hAudioLoadedText, 'String', 'engine20sec.wav');
        case 'Jet air plane'
            audioSource = 2;
            set(hAudioLoadedText, 'String', 'jetairplane16sec.wav');
        case 'Turbine'
            audioSource = 2;
            set(hAudioLoadedText, 'String', 'turbine22sec.wav');
        case 'Washing machine'
            audioSource = 2;
            set(hAudioLoadedText, 'String', 'washingmachine18sec.wav');            
        case 'Load file...' 
            fileName = uigetfile('*.*');
            if (fileName ~=0) 
                audioSource = 2;
                set(hAudioLoadedText, 'String', fileName);
            else
                audioSource = 0;
                set(hAudioLoadedText, 'String', 'White noise');
            end
        otherwise
            audioSource = 0;
            set(hAudioLoadedText, 'String', 'White noise');
    end   
    
    changeAudioFile = true;
    sendUDP();
    changeAudioFile = false;
end

function hFiltSelectCallback(source,~)
    % Called when a filter is selected from the pop-up menu
    str = get(source, 'String');
    val = get(source, 'Value');
    
    switch str{val}
        case 'A-Weighting' 
            filterNumber = 1;
        case 'C-Weighting' 
            filterNumber = 2;
        otherwise
            filterNumber = 0;
    end
   
    sendUDP();
end

function hFigDeleteCallback(~,~,~)
    % Called when the UI is closed
    release(hUDP);
end

end

