function examples = getexamples(this) %#ok<INUSD>
%GETEXAMPLES   Get the examples.

%   Copyright 2009 The MathWorks, Inc.

examples = {{ ...
    '% Design a C-message IIR filter compliant with the ',...
    '% Bell System Technical Reference 41009 standard for a sampling ',...
    '%frequency of 44.1 KHz. Return the filter with a default df2sos ',...
    '%structure. Set the SOS scaling to ''Linf''.',...
    'd = fdesign.audioweighting(''WT'',''Cmessage'',44.1e3);',...
    'Hd = design(d,''bell41009'',''SOSScaleNorm'',''Linf'');',...
    'fvtool(Hd)'}};

% [EOF]
