function h = AddStimMenuItem(sname, parentMenu);

mh = findobj('tag',[parentMenu 'Menu']);
sname = upper(sname);

uimenu(mh, 'Accelerator',  '',...
   'BusyAction',  'queue',...
   'ButtonDownFcn',  '',...
   'Callback',  'SGSRmainCallback;',...
   'Checked',  'off',...
   'Clipping',  'on',...
   'CreateFcn',  '',...
   'DeleteFcn',  '',...
   'Enable',  'on',...
   'ForegroundColor',  [0 0 0],...
   'HandleVisibility',  'on',...
   'HitTest',  'on',...
   'Interruptible',  'on',...
   'Label',  sname,...
   'Selected',  'off',...
   'SelectionHighlight',  'on',...
   'Separator',  'off',...
   'Tag',  ['Stim' sname 'menuItem'],...
   'UIContextMenu',  [],...
   'UserData',  [],...
   'Visible',  'on');

%              'Position',  1,...
%    'Parent',  mh,...
%   'Type',  'uimenu',...
%   'Children',  zeros(0,1),...


