function examples = getexamples(this)
%GETEXAMPLES Get the examples.

%   Copyright 2007 The MathWorks, Inc.

examples = {{ ...
    'Design a 90th order halfband lowpass equiripple filter with a ', ...
    '% transition width of .05.',...
    'N = 90; % Filter Order', ...
    'TW = .05; % Transition Width', ...
    'h  = fdesign.halfband(''Type'',''Lowpass'',''N,TW'',N,TW);', ...
    'Hd = design(h,''equiripple'');', ...
    'fvtool(Hd)'},...
    { ...
    'Design a 90th order halfband lowpass equiripple filter with a ', ...
    '% transition width of .05. and an increasing stopband attenuation.',...
    'N = 90; % Filter Order', ...
    'TW = .05; % Transition Width', ...
    'h  = fdesign.halfband(''Type'',''Lowpass'',''N,TW'',N,TW);', ...
    'Hd = design(h,''equiripple'',''StopbandShape'',''linear'',''StopbandDecay'',50);', ...
    'fvtool(Hd)'}};
