function y=playit(INSTR, UseET1, doGo);

% D/A conversion according to the instructions in INSTR XXX
% (see playInstr)

global SGSR PD1;

if nargin<1, error('not enough input args'); end;
if nargin<2, UseET1=1; end;
if nargin<3, doGo=1; end;

PrepareHardware4DA(INSTR.Hardware); % reset PD1, routing, fsam, nsam, etc; SS1 pre-synch switching
% load playlist(s) to dama and call APOS seqplay
loadPlayList(INSTR);
s232('seqplay', INSTR.chanDBN);
% -------CLICK DEBUG-------
s232('PD1arm',1); 
if ~doGo, pause; end;
if UseET1, SecureET1go; end; % must be started before D/A or else will miss click
% -------CLICK DEBUG-------
% tic;
% while toc<1, end;
% disp('POST SWITCHING')
s232('PD1go',1);
% ----swift rewiring for proper sound output and spike input
% connect ET1 to spike trigger device, etc.
% already figured out in function ss1switching called by playInstr.
for icomm=INSTR.Hardware.postGo.', % column-wise assignment (see help for)
   s232('SS1select', icomm(1), icomm(2), icomm(3));
end;

% set PA4s according to instructions generated by PA4settings
for icomm=INSTR.PA4.', % column-wise assignment (see help for)
   PA4atten(icomm(1), icomm(2));
end;
