%-----------------------------------------------------------------
%     DATAQUEST - Specific Parameters for CALIB datasets
%-----------------------------------------------------------------
function S = DataQuestSchema(ds)

%Make sure the returned structure S always has the same fieldnames in
%the right order ...
Template = struct( ...
    'DSSNr', NaN, ...
    'Nharm', NaN, ...
    'CorrCurve', '', ...
    'RiseDur', NaN, ...
    'FallDur', NaN);
S = structtemplate(ds.StimParam, Template, 'warning', 'off', 'reduction', 'off');

%-----------------------------------------------------------------