%-----------------------------------------------------------------
%     DATAQUEST - Specific Parameters for SCH012 datasets
%-----------------------------------------------------------------
function S = DataQuestSchema(ds)

%Make sure the returned structure S always has the same fieldnames in
%the right order ...
FreqParam = struct( ...
    'CarFreq', NaN, ...
    'CarPhase', NaN, ...
    'ModFreq', NaN, ...
    'ModPhase', NaN, ...
    'ModDepth', NaN);
GWParam = struct( ...
    'FileName', '', ...
    'ID', '', ...
    'DSNr', NaN, ...
    'NPoints', NaN, ...
    'PbPer', NaN, ...
    'NStart', NaN, ...
    'EffSPL', NaN, ...
    'CalibID', '');
ShiftGWParam = struct( ...
    'ITD1', NaN, ...
    'ITD2', NaN, ...
    'ITDRate', NaN);
Template = struct( ...
    'FreqParam', FreqParam, ...
    'GWParam', GWParam, ...
    'ShiftGWParam', ShiftGWParam, ...
    'BurstDur', NaN, ...
    'RepDur', NaN, ...
    'RiseDur', NaN, ...
    'FallDur', NaN, ...
    'Delay', NaN, ...
    'SPL', NaN);
S = structtemplate(ds.StimParam, Template, 'warning', 'off', 'reduction', 'off');

%-----------------------------------------------------------------