function thisloadobj(this, s)
%THISLOADOBJ   Load this object.

%   Author(s): J. Schickler
%   Copyright 1999-2004 The MathWorks, Inc.

set(this, ...
    'BlockLength',         s.BlockLength);

dffir_thisloadobj(this, s);

set(this, ...
    'InitFactor',          s.InitFactor, ...
    'KalmanGain',          s.KalmanGain, ...
    'ConversionFactor',    s.ConversionFactor, ...
    'FwdPrediction',       s.FwdPrediction, ...
    'BkwdPrediction',      s.BkwdPrediction, ...
    'DesiredSignalStates', s.DesiredSignalStates, ...
    'KalmanGainStates',    s.KalmanGainStates);

% [EOF]
