function staggerWFplotREL(DLAT, intensity1, intensity2)

% StaggerWFplotREL(DLAT, intensity1, intensity2)
%
% staggers curves from WFplots from the data in DLAT (generated by pslatgen_all) according to cf.
% 'intensity1' and 'intensity2' specify from which two intensities curves are taken, the magnitudes of the
% curves belonging to intensity2 are normalized with respect to those of intensity1
%
% What is plotted are the differences in delay and amplitude of the primary peak: intensity2 with respect to intensity1
%
% TF 12/09/2005

xmin1 = -0.5;
xmax1 = 0.5;
xmin2 = 0;
xmax2 = 2;
ymin = 0;
ymax = 5000;

figure;
ax1=subplot(2,1,1);
axis([xmin1 xmax1 ymin ymax]);
title(['Delay primary peak @ ' num2str(intensity2) ' dB vs delay @ ' num2str(intensity1) ' dB. Data: A0241,A0242,A0428,A0454']);
xlabel('Delay (ms)');
ylabel('CF (Hz)');
ax2=subplot(2,1,2);
axis([xmin2 xmax2 ymin ymax]);
title(['Magnitude primary peak @ ' num2str(intensity2) ' dB vs magnitude @ ' num2str(intensity1) ' dB. Data: A0241,A0242,A0428,A0454']);
xlabel('Magnitude');
ylabel('CF (Hz)');

axes(ax1);
line([(xmin1+xmax1)/2 (xmin1+xmax1)/2],[ymin ymax],'color',[0 0 0],'LineStyle','--');
axes(ax2);
line([(xmin2+xmax2)/2 (xmin2+xmax2)/2],[ymin ymax],'color',[0 0 0],'LineStyle','--');

nd = numel(DLAT);
D=DLAT;

for i=1:nd
    
    if ~isempty(find(D(i).xval==intensity1))&~isempty(find(D(i).xval==intensity2))
        idx1 = find(D(i).xval==intensity1);
        idx2 = find(D(i).xval==intensity2);
    
        nidx = idx1;
        nfactor = D(i).ppnormmagn(nidx); %the normalize factor is the height of the central peak
        D(i).normco(idx1,:) = (D(i).normco(idx1,:))/nfactor; %normalize curves to primary peak of normto-intensity
        D(i).normco(idx2,:) = (D(i).normco(idx2,:))/nfactor;
        
       
        % plot dot of delay difference of primary peaks and plot dot of amplitude ratio of primary peaks (intensity 2 vs. intensity 1)
        % (difcor data plotted as blue, non-difcor-data as red)
        if D(i).difcor == 1, 
            axes(ax1);
            line((D(i).yval(idx2)-D(i).yval(idx1)) , D(i).cf, 'LineStyle', 'none', 'Marker', 'o', ...
            'Color', [0 0 1],'MarkerFace', [1 1 1]);
            axes(ax2);
            line((D(i).ppnormmagn(idx2)/D(i).ppnormmagn(idx1)) , D(i).cf, 'LineStyle', 'none', 'Marker', 'v', ...
            'Color', [0 0 1],'MarkerFace', [1 1 1]);
        elseif D(i).difcor == 0,
            axes(ax1);
            line((D(i).yval(idx2)-D(i).yval(idx1)) , D(i).cf, 'LineStyle', 'none', 'Marker', 'o', ...
            'Color', [1 0 0],'MarkerFace', [1 1 1]);
            axes(ax2);
            line((D(i).ppnormmagn(idx2)/D(i).ppnormmagn(idx1)) , D(i).cf, 'LineStyle', 'none', 'Marker', 'v', ...
            'Color', [1 0 0],'MarkerFace', [1 1 1]);
        else, disp(['error with difcorness for row '  num2str(i)]);
        end
    end
end