function examples = getexamples(this)
%GETEXAMPLES Get the examples.

%   Copyright 2007 The MathWorks, Inc.

examples = {{ ...
    'Design a 27th order minimum-multiplier lowpass Butterworth halfband IIR filter.',...
    'N = 27; % Filter order must be odd',...
    'd = fdesign.halfband(''Type'',''Lowpass'',''N'',N);',...
    'Hd = design(d,''butter'',''FilterStructure'',''cascadeallpass'');',...
    'fvtool(Hd)'}};

% [EOF]
