function examples = getexamples(this) %#ok<INUSD>
%GETEXAMPLES   Get the examples.

%   Copyright 2009 The MathWorks, Inc.

examples = {{ ...
    '% Design a ITU-T 0.41 FIR filter for a sampling ',...
    '% frequency of 44.1 KHz. Return the filter with a ''dffirt''',...
    '% structure.',...
    'd = fdesign.audioweighting(''WT'',''ITUT041'',44.1e3);',...
    'Hd = design(d,''freqsamp'',''FilterStructure'',''dffirt'');',...
    'fvtool(Hd)'}};

% [EOF]
