#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CX1 wrapper class

class CRPcoX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CRPcoX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xD323A625, 0x1D13, 0x11D4, { 0x88, 0x58, 0x44, 0x45, 0x53, 0x54, 0x0, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName, LPCTSTR lpszWindowName, DWORD dwStyle,
						const RECT& rect, CWnd* pParentWnd, UINT nID, 
						CCreateContext* pContext = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); 
	}

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle, const RECT& rect, CWnd* pParentWnd, 
				UINT nID, CFile* pPersist = NULL, BOOL bStorage = FALSE,
				BSTR bstrLicKey = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); 
	}

// Attributes
public:


// Operations
public:

// _DRPcoX

// Functions
//

	CString GetError()
	{
		CString result;
		InvokeHelper(0x1, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
		return result;
	}
	long Connect(long Interface, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_I4 VTS_I4 ;
		InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Interface, DevNum);
		return result;
	}
	long SetTagVal(LPCTSTR Name, float Val)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_R4 ;
		InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Name, Val);
		return result;
	}
	long LoadCOF(LPCTSTR FileName)
	{
		long result;
		static BYTE parms[] = VTS_BSTR ;
		InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, parms, FileName);
		return result;
	}
	long Run()
	{
		long result;
		InvokeHelper(0x5, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
		return result;
	}
	long Halt()
	{
		long result;
		InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
		return result;
	}
	long SoftTrg(long Trg_Bitn)
	{
		long result;
		static BYTE parms[] = VTS_I4 ;
		InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Trg_Bitn);
		return result;
	}
	float GetTagVal(LPCTSTR Name)
	{
		float result;
		static BYTE parms[] = VTS_BSTR ;
		InvokeHelper(0x8, DISPATCH_METHOD, VT_R4, (void*)&result, parms, Name);
		return result;
	}
	long ReadTag(LPCTSTR Name, float * pBuf, long nOS, long nWords)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_PR4 VTS_I4 VTS_I4 ;
		InvokeHelper(0x9, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Name, pBuf, nOS, nWords);
		return result;
	}
	long WriteTag(LPCTSTR Name, float * pBuf, long nOS, long nWords)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_PR4 VTS_I4 VTS_I4 ;
		InvokeHelper(0xa, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Name, pBuf, nOS, nWords);
		return result;
	}
	long SendParTable(LPCTSTR Name, float IndexID)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_R4 ;
		InvokeHelper(0xb, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Name, IndexID);
		return result;
	}
	long SendSrcFile(LPCTSTR Name, long SeekOS, long nWords)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 VTS_I4 ;
		InvokeHelper(0xc, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Name, SeekOS, nWords);
		return result;
	}
	long GetNames(LPCTSTR NameList, long MaxNames, long ObjType)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 VTS_I4 ;
		InvokeHelper(0xd, DISPATCH_METHOD, VT_I4, (void*)&result, parms, NameList, MaxNames, ObjType);
		return result;
	}
	VARIANT ReadTagV(LPCTSTR Name, long nOS, long nWords)
	{
		VARIANT result;
		static BYTE parms[] = VTS_BSTR VTS_I4 VTS_I4 ;
		InvokeHelper(0xe, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms, Name, nOS, nWords);
		return result;
	}
	long WriteTagV(LPCTSTR Name, long nOS, VARIANT Buf)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 VTS_VARIANT ;
		InvokeHelper(0xf, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Name, nOS, &Buf);
		return result;
	}
	long GetTagSize(LPCTSTR Name)
	{
		long result;
		static BYTE parms[] = VTS_BSTR ;
		InvokeHelper(0x10, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Name);
		return result;
	}
	long GetTagType(LPCTSTR Name)
	{
		long result;
		static BYTE parms[] = VTS_BSTR ;
		InvokeHelper(0x11, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Name);
		return result;
	}
	long SetSrcFileName(LPCTSTR Name, LPCTSTR FileName)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_BSTR ;
		InvokeHelper(0x12, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Name, FileName);
		return result;
	}
	long GetNumOf(LPCTSTR ObjTypeName)
	{
		long result;
		static BYTE parms[] = VTS_BSTR ;
		InvokeHelper(0x13, DISPATCH_METHOD, VT_I4, (void*)&result, parms, ObjTypeName);
		return result;
	}
	CString GetNameOf(LPCTSTR ObjTypeName, long Index)
	{
		CString result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x14, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms, ObjTypeName, Index);
		return result;
	}
	long ReadCOF(LPCTSTR FileName)
	{
		long result;
		static BYTE parms[] = VTS_BSTR ;
		InvokeHelper(0x15, DISPATCH_METHOD, VT_I4, (void*)&result, parms, FileName);
		return result;
	}
	long ConnectRP2(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x16, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	long ConnectRL2(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x17, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	long ConnectRA16(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x18, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	VARIANT ReadTagVEX(LPCTSTR Name, long nOS, long nWords, LPCTSTR SrcType, LPCTSTR DstType, long nChans)
	{
		VARIANT result;
		static BYTE parms[] = VTS_BSTR VTS_I4 VTS_I4 VTS_BSTR VTS_BSTR VTS_I4 ;
		InvokeHelper(0x19, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms, Name, nOS, nWords, SrcType, DstType, nChans);
		return result;
	}
	long GetStatus()
	{
		long result;
		InvokeHelper(0x1a, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
		return result;
	}
	long GetCycUse()
	{
		long result;
		InvokeHelper(0x1b, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
		return result;
	}
	long ClearCOF()
	{
		long result;
		InvokeHelper(0x1c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
		return result;
	}
	long WriteTagVEX(LPCTSTR Name, long nOS, LPCTSTR DstType, VARIANT Buf)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 VTS_BSTR VTS_VARIANT ;
		InvokeHelper(0x1d, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Name, nOS, DstType, &Buf);
		return result;
	}
	long ZeroTag(LPCTSTR Name)
	{
		long result;
		static BYTE parms[] = VTS_BSTR ;
		InvokeHelper(0x1e, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Name);
		return result;
	}
	float GetSFreq()
	{
		float result;
		InvokeHelper(0x1f, DISPATCH_METHOD, VT_R4, (void*)&result, NULL);
		return result;
	}
	long ConnectRV8(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x20, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	long GetDevCfg(long Addr, long Width32)
	{
		long result;
		static BYTE parms[] = VTS_I4 VTS_I4 ;
		InvokeHelper(0x21, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Addr, Width32);
		return result;
	}
	long SetDevCfg(long Addr, long Val, long Width32)
	{
		long result;
		static BYTE parms[] = VTS_I4 VTS_I4 VTS_I4 ;
		InvokeHelper(0x22, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Addr, Val, Width32);
		return result;
	}
	long LoadCOFsf(LPCTSTR FileName, float SampFreq)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_R4 ;
		InvokeHelper(0x23, DISPATCH_METHOD, VT_I4, (void*)&result, parms, FileName, SampFreq);
		return result;
	}
	long DefStatus(long DefID)
	{
		long result;
		static BYTE parms[] = VTS_I4 ;
		InvokeHelper(0x24, DISPATCH_METHOD, VT_I4, (void*)&result, parms, DefID);
		return result;
	}
	VARIANT GetDefData(long DefID)
	{
		VARIANT result;
		static BYTE parms[] = VTS_I4 ;
		InvokeHelper(0x25, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms, DefID);
		return result;
	}
	void AboutBox()
	{
		InvokeHelper(DISPID_ABOUTBOX, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
	}
	long ConnectRM1(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x26, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	long ConnectRM2(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x27, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	long ConnectRX5(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x28, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	long ConnectRX6(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x29, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	long ConnectRX7(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x2a, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	long ConnectRX8(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x2b, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	long ConnectRX9(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x2c, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	long ConnectRZ2(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x2d, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	long ConnectRZ3(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x2e, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	long ConnectRZ4(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x2f, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	long ConnectRZ5(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x30, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}
	long ConnectRZ6(LPCTSTR IntName, long DevNum)
	{
		long result;
		static BYTE parms[] = VTS_BSTR VTS_I4 ;
		InvokeHelper(0x31, DISPATCH_METHOD, VT_I4, (void*)&result, parms, IntName, DevNum);
		return result;
	}

// Properties
//



};
