function examples = getexamples(this) %#ok<INUSD>
%GETEXAMPLES   Get the examples.

%   Copyright 2009 The MathWorks, Inc.

examples = {{ ...
    '% Design a ITU-R 468-4 FIR equiripple filter for a sampling ',...
    '% frequency of 44.1 KHz. Return the filter with a ''dffirt''',...
    '% structure.',...
    'd = fdesign.audioweighting(''WT'',''ITUR4684'',44.1e3);',...
    'Hd = design(d,''equiripple'',''FilterStructure'',''dffirt'');',...
    'fvtool(Hd)'}};

% [EOF]
