function file = HFcode(L)
% This popscript generates the code for pslatgen for high frequency-fibers,
% i.e. paragraphs like the following:
%
% %Fiber 2, high cf
% %interaural correlation -1
% List = struct('filename','M0542','iseqp',NaN,'isubseqp',NaN,'iseqn',num2cell([15,33,34,35]),'isubseqn',num2cell([1,2,2,2]),'discernvalue',num2cell([70,50,90,80]));
% T = genwfplotTF(List, 3, 'discernfieldlabel', 'Intensity', 'discernfieldunit', 'dB SPL','plot','yes'); % reference = ds 15, subseq 1
% D = [D; concatto1Row(ExtractPSentry(T, XFieldName, YFieldName),'xval','yval')];groupplot(D(numel(D)), 'xval', 'yval','xlim',[30 90],'ylim',[-1 0.7]);pause;close all;
% % interaural correlation +1
% List = struct('filename','M0542','iseqp',num2cell([15,33,34,35]),'isubseqp',num2cell([2,1,1,1]),'iseqn',NaN,'isubseqn',NaN,'discernvalue',num2cell([70,50,90,80]));
% T = genwfplotTF(List, 3, 'discernfieldlabel', 'Intensity', 'discernfieldunit', 'dB SPL','plot','yes'); % reference = ds 15, subseq 2
% D = [D; concatto1Row(ExtractPSentry(T, XFieldName, YFieldName),'xval','yval')];groupplot(D(numel(D)), 'xval', 'yval','xlim',[30 90],'ylim',[-1 0.7]);pause;close all;
%
% The program uses the fibers in a struct array L, generated by selectsplitFibers.m

line1 = '%Fiber FNR, high cf';
line2 = '%interaural correlation -1';
line3 = 'List = struct(''filename'',''FILENAME'',''iseqp'',num2cell(POSSEQ),''isubseqp'',num2cell(POSSUBSEQ),''iseqn'',NaN,''isubseqn'',NaN,''discernvalue'',num2cell(SPLS);';
line4 = 'T = genwfplotTF(List, RANK, ''discernfieldlabel'', ''Intensity'', ''discernfieldunit'', ''dB SPL'',''plot'',''yes''); % reference = ds REFDS, subseq REFSUBSEQ';
line5 = 'D = [D; concatto1Row(ExtractPSentry(T, XFieldName, YFieldName),''xval'',''yval'')];groupplot(D(numel(D)), ''xval'', ''yval'',''xlim'',[30 90],''ylim'',[-1 0.7]);pause;close all;';
line6 = '% interaural correlation +1';
line7 = 'List = struct(''filename'',''FILENAME'',''iseqp'',NaN,''isubseqp'',NaN,''iseqn'',num2cell(NEGSEQ),''isubseqn'',num2cell(NEGSUBSEQ),''discernvalue'',num2cell(SPLS);';
line8 = 'T = genwfplotTF(List, RANK, ''discernfieldlabel'', ''Intensity'', ''discernfieldunit'', ''dB SPL'',''plot'',''yes''); % reference = ds REFDS, subseq REFSUBSEQ';

for i=1:numel(L)
   
    if(isequal(L(i).freqgroup, 'hi')
        fnr=L(i).fibernr; fn = L(i).filename;
        
        line1 = strrep(line1,'FNR',fnr);
        line3 = strrep(line3,'FILENAME',fn);
        line3 = strrep(line3,'POSSEQ',getseq(fn,fnr,1));
        line3 = strrep(line3,'POSSUBSEQ',getsubseq(fn,fnr,1));
        line3 = strrep(line3,'SPLS',getspls(fn,fnr));
        line4 = strrep(line4,'RANK',getrank(fn,fnr));
        line4 = strrep(line4,'REFDS',getrefds(fn,fnr));
        line4 = strrep(line4,'REFSUBSEQ',getrefds(fn,fnr));
        line7 = strrep(line7,'NEGSEQ',getseq(fn,fnr,-1));
        line7 = strrep(line7,'NEGSUBSEQ',getsubseq(fn,fnr,-1));
        line7 = strrep(line7,'SPLS',getspls(fn,fnr));
        line8 = strrep(line8,'RANK',getrank(fn,fnr));
        line8 = strrep(line8,'REFDS',getrefds(fn,fnr));
        line8 = strrep(line8,'REFSUBSEQ',getrefds(fn,fnr));
    end
end

%-----------------------------------------------------local functions-----------------------------------------------------
function seq = getseq(fn, fnr)

type = decideData(fn,fnr);

%-------------------------------------------------------------------------------------------------------------------------
function sseq = getsubseq(fn,fnr)

%-------------------------------------------------------------------------------------------------------------------------
function type = decideData(fn,fnr)



