%-----------------------------------------------------------------
%     DATAQUEST - Specific Parameters for ARMIN datasets
%-----------------------------------------------------------------
function S = DataQuestSchema(ds)

%Check for dataset with newer version of the stimulus type and warn
%the user ...
VERSION = 3.0; VerFieldName = 'AKversion';
if ~isfield(ds.StimParam, VerFieldName), warning(sprintf('Failed to do version check on dataset %s.', ds.title));
elseif (getfield(ds.StimParam, VerFieldName) > VERSION), warning(sprintf('Dataset %s found that has newer version than script was intended for.', ds.title)); end

%Make sure the returned structure S always has the same fieldnames in
%the right order ...
Template = struct( ...
    'AKversion', NaN, ...
    'seedC', NaN, ...
    'seedVlow', NaN, ...
    'seedVhigh', NaN, ...
    'polaconst', NaN, ...
    'polalow', NaN, ...
    'polahigh', NaN, ...
    'ConstEar', NaN, ...
    'VarEar', NaN, ...
    'loflip', NaN, ...
    'hiflip', NaN, ...
    'dflip', NaN, ...
    'flipstepunit', '', ...
    'reps', NaN, ...
    'interval', NaN, ...
    'order', NaN, ...
    'burstDur', NaN, ...
    'riseDur', NaN, ...
    'fallDur', NaN, ...
    'delay', NaN, ...
    'Flow', NaN, ...
    'Fhigh', NaN, ...
    'SPL', NaN, ...
    'active', NaN);
S = structtemplate(ds.StimParam, Template, 'warning', 'off', 'reduction', 'off');

%-----------------------------------------------------------------