%-----------------------------------------------------------------
%      DATAQUEST - Specific Parameters for EREV datasets
%-----------------------------------------------------------------
function S = DataQuestSchema(ds)

%Make sure the returned structure S always has the same fieldnames in
%the right order ...
Template = struct( ...
    'SPLtone', NaN, ...
    'active', NaN, ...
    'SPLnoise', NaN, ...
    'Ntoken', NaN, ...
    'TotDur', NaN, ...
    'NoiseDur', NaN, ...
    'NoiseRep', NaN, ...
    'AdaptDur', NaN, ...
    'NoiseBW', NaN, ...
    'ToneFreq', NaN, ...
    'FreqPos', NaN, ...
    'SpecType', NaN, ...
    'RejectAtt', NaN, ...
    'RejectFreq', [NaN NaN], ...
    'RampDur', NaN, ...
    'Rseed', NaN);
S = structtemplate(ds.StimParam, Template, 'warning', 'off', 'reduction', 'off');

%-----------------------------------------------------------------