%-----------------------------------------------------------------
%     DATAQUEST - Specific Parameters for SCH008 datasets
%-----------------------------------------------------------------
function S = DataQuestSchema(ds)

%Make sure the returned structure S always has the same fieldnames in
%the right order ...
ThrCurveParam = struct( ...
    'CritNr', NaN, ...
    'MaxSPL', NaN, ...
    'NSponRec', NaN, ...
    'MeanSA', NaN, ...
    'StdSA', NaN, ...
    'TrgSA', NaN, ...
    'TrgSI', NaN);
GenStimParam = struct( ...
    'BurstDur', NaN, ...
    'RepDur', NaN, ...
    'RiseDur', NaN, ...
    'FallDur', NaN, ...
    'Delay', NaN, ...
    'SPL', NaN);
Template = struct( ...  
    'ThrCurveParam', ThrCurveParam, ...
    'GenStimParam', GenStimParam, ...
    'lofreq', NaN, ...
    'dfreq', NaN, ...
    'hifreq', NaN, ...
    'cfreqs', NaN, ...
    'stepunit', '', ...
    'silence', NaN, ...
    'interval', NaN, ...
    'order', NaN, ...
    'burstDur', NaN, ...
    'riseDur', NaN, ...
    'fallDur', NaN, ...
    'delay', NaN, ...
    'SPL', NaN, ...
    'active', NaN, ...
    'stepSize', NaN, ...
    'startSPL', NaN, ...
    'Nrev', NaN, ...
    'critMode', '', ...
    'critVal', NaN, ...
    'minSPL', NaN);
S = structtemplate(ds.StimParam, Template, 'warning', 'off', 'reduction', 'off');

%-----------------------------------------------------------------