%-----------------------------------------------------------------
%      DATAQUEST - Specific Parameters for THR datasets
%-----------------------------------------------------------------
function S = DataQuestSchema(ds)

%Make sure the returned structure S always has the same fieldnames in
%the right order ...
Template = struct( ...
      'lofreq', NaN, ...
       'dfreq', NaN, ...
      'hifreq', NaN, ...
      'cfreqs', NaN, ...
    'stepunit', '', ...
     'silence', NaN, ...
    'interval', NaN, ...
       'order', NaN, ...
    'burstDur', NaN, ...
     'riseDur', NaN, ...
     'fallDur', NaN, ...
       'delay', NaN, ...
         'SPL', NaN, ...
      'active', NaN, ...
    'stepSize', NaN, ...
    'startSPL', NaN, ...
        'Nrev', NaN, ...
    'critMode', '', ...
     'critVal', NaN, ...
      'minSPL', NaN);
S = structtemplate(ds.StimParam, Template, 'warning', 'off', 'reduction', 'off');

%-----------------------------------------------------------------