%-----------------------------------------------------------------
%     DATAQUEST - Specific Parameters for SCH005 datasets
%-----------------------------------------------------------------
function S = DataQuestSchema(ds)

%Make sure the returned structure S always has the same fieldnames in
%the right order ...
EffSPLComp = struct( ...
    'DSSNr', NaN, ...
    'EffSPL', NaN, ... 
    'CalibID', NaN);
Template = struct( ...
    'EffSPLComp', EffSPLComp, ...
    'NPoints', NaN, ...
    'PbPer', NaN, ...
    'Code', NaN, ...
    'RandSeed', NaN);
S = structtemplate(ds.StimParam, Template, 'warning', 'off', 'reduction', 'off');

%-----------------------------------------------------------------