function ps = mypointershape(x);
switch x
case '?',
s = strvcat(...
   '                '  ,...
   '                '  ,...
   '          OO    '  ,...
   '       OO##OOO  '  ,...
   '      ### ###O  '  ,...
   '     ##     ##O '  ,...
   '     #      ##  '  ,...
   '          ##    '  ,...
   '         ##     '  ,...
   '        ##O     '  ,...
   '        ##      '  ,...
   '          O     '  ,...
   '         #OO    '  ,...
   '        ###     '  ,...
   '         #      '  ,...
   '                '  ,...
   '                '  ...
   );
otherwise
   error('Unknown pointer shape.');
end
ps = localStrToVal(s);


function v = localStrToVal(s);
% expand/truncate to 16x16 matrix 
sz = size(s);
if sz(2)<16,
   s = [s repmat(' ',sz(1), 16-sz(2))];
end
if sz(1)<16,
   s = [s; repmat(' ', 16-sz(1), 16)];
end
s = s(1:16,1:16);
% # -> 1; O = 2; other -> nan
v = nan+zeros(size(s));
v(find(s=='#')) = 1;
v(find(s=='O')) = 2;
