function ArgOut = ManageRAPStatus(varargin)
%ManageRAPStatus  manages RAPStatus structure
%   RAPStat = ManageRAPStatus returns a structure defining the initial RAP
%   status.
%
%   DefValue = ManageRAPStatus(FieldName) returns the default value of the
%   field given by FieldName. FieldName can be recursive.
%
%   Attention! This function is an internal function belonging to the RAP 
%   project and should not be invoked from the MATLAB command prompt.

%B. Van de Sande 02-08-2005

RAPStat = DefineRAPStat;

if (nargin == 0)
    ArgOut = RAPStat;
else %Default value for specific field ...
    % Split fieldname, delimiter is "."
    FieldName = varargin{1};
    Tokens = Words2cell(FieldName, '.');
    NTokens = length(Tokens);
    
    % Go inside RAPStat by the supplied fieldnames
    ArgOut = RAPStat;
    for n = 1:NTokens
        ArgOut = ArgOut.(Tokens{n});
    end
end
    
%------------------------------local functions------------------------------
function RAPStat = DefineRAPStat

%---------------------------------------------------------------------------
%                           General parameters
%---------------------------------------------------------------------------
%These parameters are altered by the following functions: DF, DS, NX DS and 
%ID ...

DataFile     = '';         %Filename of current datafile ...
FullFileName = '';         %Full path, filename and extension of current 
                           %datafile ...
LUT          = struct([]); %LUT of current datafile ...
%Second dataset serves as a background dataset, it cannot directly be altered.
%Swapping between the foreground and background dataset is the only way in which
%the second dataset can be changed ...
SeqNr        = [];         %Current or foreground dataset ...    
DS           = [];         
SeqNr2       = [];         %Background dataset ...
DS2          = [];         

%Synchronisation with userdata interface ...
SyncUDI      = 'auto'; %Must be 'auto' or 'man'(ual) ...

GenParam = CollectInStruct(DataFile, FullFileName, LUT, SeqNr, DS, SeqNr2, DS2, SyncUDI);

%---------------------------------------------------------------------------
%                          Calculation parameters
%---------------------------------------------------------------------------
%These parameters are altered by RR, TR, AW, RW, NB, HI, MIN IS and SUB ...

SubSeqs     = 'def';   %'def' or vector specifying the subsequences (or variable
                       %ranges) to include ... (RR)
Reps        = 'def';   %'def' or vector specifying the repetitions (or trials)
                       %to include ... (TR)
AnWin       = 'def';   %The analysis window ... (AW)
ReWin       = 'def';   %The reject window ... (RW)
NBin        = 'def';   %The number of bins used for histograms ... (NB)
BinWidth    = NaN;     %Binwidth in ms used for histograms. If number of bins is set, 
                       %which is the case by default, this parameters is not used and
                       %therefore set to NaN (and vice versa) ... (BW)
BinFreq     = 'def';   %The bining frequency for cycle histograms ... (HI BI, HI BFI)
MinISI      = 'def';   %The minimum interspike interval, thus if this variable is
                       %set to 2ms, and there are two spikes within 1 millisec of 
                       %each other, then the second of those spikes is not included
                       %in the analysis ... (MIN IS)
ConSubTr    = 'def';   %The specified time (in milliseconds) is subtracted from each
                       %spike time before any analysis or window is applied to it. 
                       %This command should be used sparingly in special cases (e.g. 
                       %to correct for a fixed delay in the stimulus delivery). Note 
                       %that the analysis window is applied after subtraction ... (SUB)
CorBinWidth = 'def';   %Default binwidth for correlograms ... (BWCOR)                       
CorMaxLag   = 'def';   %Maximum lag in ms used for correlograms ... (MLCOR)
PhaseConv   = 'def';   %Phase convention ... (PHCONV)
CompDelay   = 'def';   %Compensating delay ... (COMDEL)
UnWrapping  = 'def';   %Phase unwrapping ... (UP)
RayCrit     = 'def';   %Boundary significance for Raleigh criterion ... (RY)
IntNCycles  = 'def';   %Restrict analysis window to an integer number of cyles ... (CYCLEINT)
AvgWin      = 'def';   %Averaging window in regularity analysis ... (SET RGL WIN)
MinNInt     = 'def';   %Minimum number of intervals necessary in a bin for the regularity
                       %analysis ... (SET RGL MINSPK)
HistRunAv   = 'def';   %Running average range on histograms ... (SM HIS)
CurveRunAv  = 'def';   %Running average range on other curves ... (SM LIN)
PklRunAv    = 'def';   %Runnning average range used in the calculation of the peak
                       %latency ... (SM PKL)
EnvRunAv    = 'def';   %Running average range on the envelope of DifCor ... (SM ENV)
PklRateInc  = 'def';   %Rate increase for measurement of beginning of peak ... (PER PKL)
PklSrWin    = 'def';   %Spontaneous rate window for estimation of spontaneous rate ... (SET PKL SSW)
PklPkWin    = 'def';   %Peak window ... (SET PKL PKW)
ThrQ        = 'def';   %Q-factor threshold for Threshold Curves ... (SET TH Q)
SyncThr     = 'def';   %Cutoff threshold on synchronisation curve ... (SET SYNC THR)
MaxPST      = 'def';   %The maximum post-stimulus time, this parameter is never applied
                       %on a dataset ... 
MaxISI      = 'def';   %The maximum interspike interval ... only used for calculation
                       %of ISI histogram, this is never applied on a dataset ...
MaxFSL      = 'def';   %Maximum latency used in the FSL histogram, this parameter is
                       %never applied on a dataset ...
SignLevel   = 'def';   %Significance level for the coincidence rate plot (CR) ...
BootStrap   = 'def';   %Boot strap for the coincidence rate plot (CR) ...
                       
%See GetRAPCalcParam.m for default values of these parameters. The default values are
%administrated by another function because of their dependence on the dataset being
%loaded ...
%Attention! MinISI and ConSubst alter the actual spiketimes and override the 
%general rule that experimental data is never changed ...

CalcParam = CollectInStruct(SubSeqs, Reps, AnWin, ReWin, NBin, BinWidth, BinFreq, MinISI, ConSubTr, ...
    CorMaxLag, CorBinWidth, PhaseConv, CompDelay, UnWrapping, RayCrit, IntNCycles, AvgWin, MinNInt, HistRunAv, ...
    CurveRunAv, PklRunAv, EnvRunAv, PklRateInc, PklSrWin, PklPkWin, ThrQ, SyncThr, MaxPST, MaxISI, MaxFSL, ...
    SignLevel, BootStrap);
                        
%These calculation parameters are accompanying the background dataset ... Swapping the
%fore- and background dataset also swaps these calculation parameters ...
SubSeqs  = 'def';
Reps     = 'def';
AnWin    = 'def';
ReWin    = 'def';
ConSubTr = 'def';
MinISI   = 'def';

CalcParam2 = CollectInStruct(SubSeqs, Reps, AnWin, ReWin, ConSubTr, MinISI);
                        
%---------------------------------------------------------------------------
%                            Command Line parameters
%---------------------------------------------------------------------------
%Mainly used for restricting the output when executing macro's ...

Verbose = 'yes';       %Should be 'yes' or 'no' ...
More    = 'off';       %Should be 'on' or 'off' ...
if strcmpi(CompuName, 'oto') && strcmpi(username, 'bram')
    Warning = 'backtrace'; %Should be 'backtrace', 'on' or 'off' ...
else
    Warning = 'on'; 
end
InMco   = 'no';        %Should be 'yes' or 'no' ...
McoEcho = 'off';       %Should be 'on' or 'off' ...
McoName = 'CLI';       %Name of macro in which code is executed (CLI = Command Line Interface) ...

ComLineParam = CollectInStruct(Verbose, More, Warning, InMco, McoEcho, McoName);

%---------------------------------------------------------------------------
%                              Plot parameters
%---------------------------------------------------------------------------
%These parameters are changed by a reduced set of RAP commands and some 
%different interpretation may be given:
%       Labels     -> TickLabels
%       Titles     -> AxesLabels
%       Caption    -> AxesTitle
%       Legend     -> AxesText
%       PageLegend -> PageHeader

%Parameters that specify figure properties ...
Figure.Caption          = 'RAP Figure'; %Standard caption is 'RAP Figure' ...
Figure.Layout.Requested = [NaN NaN]; %Rectangular distributions of plots on figure,
Figure.Layout.Current   = [NaN NaN]; %filling is started at the upper left corner and
Figure.Layout.UniDef    = [1 1];     %goes from left to right and down to bottom ...
Figure.Layout.MultiDef  = [3 2];     %The default figure organisation depends on
                                     %the type of plot ...
%Figure organisation depends on computer, because different printer drivers for the
%HP LaserJet 4050N affect the way MATLAB prints figures when setting the figure
%property 'PaperPositionMode' is set to 'auto'. This property results in MATLAB
%printing WYSIWYG... In RAP this property must be set to 'auto', because of the
%resize callback function attached to an RAP figure!
if strcmpi(CompuName, 'OTO'), %Older printer driver on OTO doesn't give any problems ...
    Figure.LeftMargin   = 0.10;      %In normalized coordinates ...
    Figure.RightMargin  = 0.05;      %In normalized coordinates ...
    Figure.HorAxSpacing = 0.075;     %In normalized coordinates ...
    Figure.UpperMargin  = 0.05;      %In normalized coordinates ...
    Figure.LowerMargin  = 0.10;      %In normalized coordinates ...
    Figure.VerAxSpacing = 0.10;      %In normalized coordinates ...
elseif strcmpi(CompuName, 'GEEK'), %Different settings for LAPTOP PXJ ... 
    Figure.LeftMargin   = 0.12;      %In normalized coordinates ...
    Figure.RightMargin  = 0.08;      %In normalized coordinates ...
    Figure.HorAxSpacing = 0.075;     %In normalized coordinates ...
    Figure.UpperMargin  = 0.00;      %In normalized coordinates ...
    Figure.LowerMargin  = 0.17;      %In normalized coordinates ...
    Figure.VerAxSpacing = 0.10;      %In normalized coordinates ...
else %On all other computers newer drivers are installed which result in MATLAB bug ...
    Figure.LeftMargin   = 0.12;      %In normalized coordinates ...
    Figure.RightMargin  = 0.08;      %In normalized coordinates ...
    Figure.HorAxSpacing = 0.075;     %In normalized coordinates ...
    Figure.UpperMargin  = 0.00;      %In normalized coordinates ...
    Figure.LowerMargin  = 0.12;      %In normalized coordinates ...
    Figure.VerAxSpacing = 0.10;      %In normalized coordinates ...
end
Figure.Hdl   = NaN;       %Handle of figure being assembled ...
Figure.CurAx = [1 1];     %Location of current axis ...
Figure.Visible = 'on';    %Creation of a visible figure is not necessary when using PL 
                          %commando for redirecting output to printer ... (NOT YET IMPLEMENTED)

%Header properties ...
if strcmpi(CompuName, 'OTO'), 
    Header.HorMargin    = 0.005; %In normalized coordinates ...
    Header.VerMargin    = 0.005; %In normalized coordinates ...
    Header.Height       = 0.10;  %In normalized coordinates ...
elseif strcmpi(CompuName, 'GEEK'), 
    Header.HorMargin    = 0.08;  %In normalized coordinates ...
    Header.VerMargin    = 0.10;  %In normalized coordinates ...
    Header.Height       = 0.10;  %In normalized coordinates ...
else
    Header.HorMargin    = 0.08;  %In normalized coordinates ...
    Header.VerMargin    = 0.05;  %In normalized coordinates ...
    Header.Height       = 0.10;  %In normalized coordinates ...
end
Header.MaxNLines    = 5;
Header.TextSpacing  = 0.005; %In normalized coordinates ...
Header.FontName     = 'arial';
Header.FontSize     = (1 - (Header.MaxNLines+1)*Header.TextSpacing)/Header.MaxNLines;
Header.Color        = [0 0 0];
Header.Hdl          = NaN;   %Keeping track of header handle is necessary because
                             %of resize function ...
                             
%DateBox properties ...
DateBox.Visible     = 'on';    %Display datebox 'on' or 'off' ...
DateBox.Pos         = [Header.HorMargin Header.VerMargin]; %In normalized coordinates ...    
DateBox.Height      = 0.01;    %In normalized coordinates of figure ...
DateBox.Alignment   = 'ver';   %'ver'(tical) or 'hor'(izontal) ...
DateBox.FontName    = 'arial';
DateBox.Color       = [0 0 0]; %Color of text and border ...
DateBox.Hdl         = NaN;     %Handle of axes object in 

%Axis properties ...
Axis.Title.Label     = '';            %Title for axis object depends on 
                                      %kind of plot ...
Axis.Title.FontName  = 'arial';       
Axis.Title.FontSize  = 0.07;          %Fontsize is given as a fraction of the
                                      %height of the parent axis ...
Axis.Title.Color     = [0 0 0];

Axis.X.Limits    = [-Inf +Inf];       %Infinity designates auto-scaling ...
Axis.X.Scale     = 'auto';            %'log', 'linear' (MATLAB property
                                      %values) or 'auto' which designates 
                                      %automatic scaling (only useful for threshold
                                      %curves) ...
Axis.X.Location  = 'bottom';          %'bottom' or 'top' (MATLAB property
                                      %values) ...
Axis.X.TickInc   = 'auto';
Axis.X.Color     = [0 0 0];
Axis.X.Margin    = 0;                 %Auto-scaling margin in percent ...
Axis.X.Flip      = 'no';              %Flip abcissa 'yes' or 'no' ...
Axis.X.Label.String    = '';
Axis.X.Label.FontName  = 'arial';
Axis.X.Label.FontSize  = 0.05;        %Fontsize is given as a fraction of the
                                      %height of the parent axis ...
Axis.X.Label.Color     = [0 0 0];

Axis.Y.Limits    = [-Inf +Inf];       %Infinity designates auto-scaling ...
Axis.Y.Scale     = 'auto';            %'log', 'linear' or 'auto' ...
Axis.Y.Location  = 'left';            %'left' or 'right' ...
Axis.Y.TickInc   = 'auto';
Axis.Y.Color     = [0 0 0];
Axis.Y.Margin    = 0.05;              %Auto-scaling margin in percent ...
Axis.Y.Label.String    = '';
Axis.Y.Label.FontName  = 'arial';
Axis.Y.Label.FontSize  = 0.05;
Axis.Y.Label.Color     = [0 0 0];

Axis.Text.FontName  = 'arial';       %Fontname used for text on axis object ...
Axis.Text.FontSize  = 0.05;          %The fontsize for this text, as a fraction 
                                     %of the height of the parent axes ...
Axis.Text.Color     = [0 0 0];       %The color of the text ...
Axis.Text.SubSeq     = 'on';         %What kind of information needs to be plotted ...
Axis.Text.CalcParam  = 'on';
Axis.Text.CalcParam2 = 'on';
Axis.Text.CalcData   = 'on';
Axis.Text.Location.SubSeq     = 'ul';%Location of text on subsequence information, 
Axis.Text.Location.CalcParam  = 'lr';%on the applied calculation parameters and on
Axis.Text.Location.CalcParam2 = 'll';%the extracted parameters ...
Axis.Text.Location.CalcData   = 'ur'; 

Axis.Tic.FontName   = 'arial';       %Attention! The fontname and size of the
Axis.Tic.FontSize   = 0.025;         %tick labels is changed by setting the
                                     %fontname and size of the axis object ...
                                     %Fontsize is given as a fraction of the
                                     %parent axis ...

Axis.LineWidth      = 0.5;           %Linewidth of the X-axis and Y-axis ...
Axis.Box            = 'off';         %'on' or 'off' ...
Axis.TickDir        = 'out';         %'in' or 'out' (MATLAB property
                                     %values) ...
Axis.Color          = [1 1 1];       %Background color of the axis object ...
Axis.MaxFontSize    = 0.40;          %Maximum fontsize in centimeters ...
Axis.MinFontSize    = 0.20;          %Minimum fontsize in centimeters ...
Axis.Hdl            = NaN;           %Handle of last axes object created ...
                                     %When an axis object is created in RAP 
                                     %then it is also finsihed completely, no
                                     %additional data should afterwards be 
                                     %plotted on the axis ...

%Parameters concerning the visualization of the analysis window ... This is
%used on PST histograms and on spike RASTER plots ...
if ischar(AnWin)
    clear('AnWin');
end

AnWin.FaceColor = [0.9 0.9 0.9];      %Color of the patch, to indicate the
AnWin.EdgeColor = [0 0 0];            %analysis window ([1 1 1] as FaceColor indicates transparant) ...
AnWin.LineStyle = '-';                %Standard a full line ...
AnWin.LineWidth = 0.5;                %0.5 points is default ...
                                     
%Parameters concerning all threshold curves ...
Thr.LineColor      = [0 0 1];         %Blue is the standard color ...
Thr.LineStyle      = '-';             %Standard a full line ...
Thr.LineWidth      = 0.5;             %0.5 points is default ...
Thr.Marker         = '.';             %Standard marker is the dot ...
Thr.Q10.LineColor  = [1 0 0];         %Red is the standard color ...
Thr.Q10.LineStyle  = '-';
Thr.Q10.LineWidth  = 0.5;
Thr.CF.Color       = [1 0 0];         %The CF is indicated with a red
Thr.CF.Marker      = 'o';             %circle ...   

%Parameters concerning all rate curves ...
Rate.LineColor           = [0 0 1];        %Blue is the standard color ...
Rate.LineStyle           = '-';            %Standard a full line ...
Rate.LineWidth           = 0.5;            %0.5 points is default ...
Rate.Marker              = '.';            %Standard marker is the dot ...
Rate.YAxisUnit           = 'rate';         %'rate' or 'count' ...
Rate.ErrorBars.Plot      = 'yes';          %'yes' or 'no' ...
Rate.ErrorBars.LineColor = [1 0 0];        %Red is the standard color ...
Rate.ErrorBars.LineStyle = '-';            %Standard a full line ...
Rate.ErrorBars.LineWidth = 0.5;            %0.5 points is default ...

%Parameters concerning all raster plots ...
Raster.Colors       = [0 0 0];        %Colors to be used (no map, only one color) ...
Raster.LineWidth    = 0.5;            %0.5 points is default ...

%Parameters concerning all histograms ...
Hist.FaceColor       = [0.4 0.4 0.4]; %Color with which bars are filled (grey) ...
Hist.EdgeColor       = [0.4 0.4 0.4]; %Color of the edges ... (same grey)
Hist.Style           = 'bars';        %'bars', 'outline' ...
Hist.YAxisUnit       = 'rate';        %'rate', 'count' or 'norm' ...
Hist.LineStyle       = '-';           %Standard a full line ...
Hist.LineWidth       = 0.5;           %0.5 points is default ...
Hist.Sort            = 'hist';        %'hist', 'line'

%Parameters concerning all polar plots ...
Pol.LineStyle        = '-';           %Standard a full line ...
Pol.LineWidth        = 0.5;           %0.5 points is default ...
Pol.LineColor        = [0 0 1];       %Blue is the standard color ...
Pol.Marker           = 'none';        %Standard marker is the dot ...

%Parameters concerning all correlograms ...
Corr.LineColor      = [0 0 1];        %Blue is the standard color ...
Corr.LineStyle      = '-';            %Standard a full line ...
Corr.LineWidth      = 0.5;            %0.5 points is default ...
Corr.Marker         = 'none';         %Standard marker is the dot ...
Corr.YAxisUnit      = 'rate';         %'norm', 'rate' or 'count' ...
Corr.ZeroLine.LineColor = [0 0 0];    %Black is the standard color ...
Corr.ZeroLine.LineStyle = ':';        %Standard a dotted line ...
Corr.ZeroLine.LineWidth = 0.5;        %0.5 points is default ...
Corr.HHWLine.LineColor = [0 0 0];     %Black is the standard color ...
Corr.HHWLine.LineStyle = '-';         %Standard a full line ...
Corr.HHWLine.LineWidth = 0.5;         %0.5 points is default ...
Corr.Env.LineColor = [0 0 0];         %Black is the standard color ...
Corr.Env.LineStyle = ':';             %Standard a full line ...
Corr.Env.LineWidth = 0.5;             %0.5 points is default ...

%Parameters concerning all vector strength curves ...
Vs.LineColor      = [0 0 1];        %Blue is the standard color ...
Vs.LineStyle      = '-';            %Standard a full line ...
Vs.LineWidth      = 0.5;            %0.5 points is default ...
Vs.Marker         = 'o';            %Standard marker is the circle ...
Vs.YAxisUnit      = 'cyc';          %'cyc' or 'rad' ...
Vs.Axis.Y.Limits  = [0 1];          %No autoscaling on Y-axis...

%Parameters concerning all sync rate curves ...
Sr.LineColor      = [0 0 1];        %Blue is the standard color ...
Sr.LineStyle      = '-';            %Standard a full line ...
Sr.LineWidth      = 0.5;            %0.5 points is default ...
Sr.Marker         = 'o';            %Standard marker is the circle ...
Sr.YAxisUnit      = 'rate';         %'rate' or 'count'...
Sr.Axis.Y.Limits  = [0 1];          %No autoscaling on Y-axis...

%Parameters concerning all Rayleigh curves ...
Ry.LineColor      = [0 0 1];        %Blue is the standard color ...
Ry.LineStyle      = '-';            %Standard a full line ...
Ry.LineWidth      = 0.5;            %0.5 points is default ...
Ry.Marker         = 'o';            %Standard marker is the circle ...
Ry.YAxisUnit      = 'count';        %Only 'count'
Ry.Axis.Y.Limits  = [0 1];          %No autoscaling on Y-axis...


%Parameters concerning all regularity analysis curves ...
Rgl.YAxisUnit     = 'cv';           %'cv' or 'mean' ...
Rgl.Avg.LineColor = [0 0 1];        %Blue is the standard color for the curve of
                                    %average interval length ...
Rgl.Avg.LineStyle = '-';            %Standard a full line ...
Rgl.Avg.LineWidth = 0.6;            %0.6 points is default ...
Rgl.Std.LineColor = [1 0 0];        %Red is the standard color for the curve of
                                    %standard deviation on the interval length ...
Rgl.Std.LineStyle = ':';            %Standard a dotted line ...
Rgl.Std.LineWidth = 0.4;            %0.4 points is default ...
Rgl.CV.LineColor = [0 0 1];         %Blue is the standard color for the coefficient
                                    %of variation ...
Rgl.CV.LineStyle = '-';             %Standard a full line ...
Rgl.CV.LineWidth = 0.5;             %0.5 points is default ...
%Parameters concerning scatter plots ...
Scp.LineColor      = [0 0 1];       %Blue is the standard color ...
Scp.LineStyle      = '-';           %Standard a full line ...
Scp.LineWidth      = 0.5;           %0.5 points is default ...
Scp.Marker         = 'o';           %Standard marker is the circle ...
%Parameters concerning trial rate distribution plots ...
Trd.YAxisUnit         = 'rate';     %'count' or 'rate' ...
Trd.LineColor         = [0 0 1];    %Blue is the standard color ...
Trd.LineStyle         = '-';        %Standard a full line ...
Trd.LineWidth         = 0.5;        %0.5 points is default ...
Trd.Marker            = 'none';     %Standard marker is the circle ...
Trd.AvgLine.LineColor = 'k';        %Black is the standard color ...
Trd.AvgLine.LineStyle = '-.';       %Standard a dotted line ...
Trd.AvgLine.LineWidth = 0.5;        %0.5 points is default ...
Trd.StdLine.LineColor = 'k';        %Black is the standard color ...
Trd.StdLine.LineStyle = ':';        %Standard a dotted line ...
Trd.StdLine.LineWidth = 0.5;        %0.5 points is default ...

%Parameters for the coincidence rate plot ...
Cr.LineColor      = [0 0 1];        %Blue is the standard color ...
Cr.LineStyle      = '-';            %Standard a full line ...
Cr.LineWidth      = 0.5;            %0.5 points is default ...
Cr.Marker         = 'o';            %Standard marker is the dot ...
Cr.YAxisUnit      = '';             %'norm', 'rate' or 'count' ...

PlotParam = CollectInStruct(Figure, Header, DateBox, Axis, AnWin, Thr, Rate, ...
    Raster, Hist, Pol, Corr, Vs, Sr, Ry, Rgl, Scp, Trd, Cr);

%---------------------------------------------------------------------------
%                               RAP Memory
%---------------------------------------------------------------------------
%Altered by the command GV and by standard binary operator functions on
%memory variables ...

Memory.V = cell(0); %Memory for numeric variables ...
Memory.C = cell(0); %Memory for character variables ...

%---------------------------------------------------------------------------
%                              Calculated Data
%---------------------------------------------------------------------------
%This data can be retrieved by the use of substitution variables ...

%X and Y arrays form most recent plot ...        
XData       = [];     %X-var values (XVAR) ...
YData       = [];     %Y-var values (YVAR) ...
%Data from the most recent Threshold curve (TH) ...
Thr.CF      = [];     %Center frequency ... (THCF)
Thr.minThr  = [];     %Minimum threshold ... (THTHR)
Thr.Q       = [];     %Estimated Q-factor ... (THQ)
Thr.BW      = [];     %Estimated bandwidth ... (THBW)
Thr.BWx     = [];     %Bandwidth start and end ...
Thr.SponAct = [];     %Spontaneous activity ... (THSPON)
%Data from the most recent Response Area (RA) plot ...
Rate.MaxVal = [];     %Maximum value ... (VALMAX)
Rate.MinVal = [];     %Minimum value ... (VALMIN)
Rate.XatMax = [];     %X-value at maximum ... (XVMAX)
Rate.XatMin = [];     %X-value at minimum ... (XVMIN)
Rate.YatMax = [];     %Y-value at maximum ... (YVMAX)
Rate.YatMin = [];     %Y-value at minimum ... (YVMIN)
Rate.NumX   = [];     %Number of X-values ... (NUMXVAR)
Rate.NumY   = [];     %Number of Y-values ... Only if two independent variables 
                      %are used ... (NUMYVAR)
%No data extracted from a Raster Plot ...                      
%Data from the most recent histogram plot ...
Hist.BinWidth = [];   %Binwidth in ms ... (BINW)
%Data from the most recent Post Stimulus Time histograms (PST) ...
PST.NSpk    = [];     %Maximum number of spikes ... (NSPKMAX)
%Data from the most recent Cycle Histogram (CH) ...
Cyc.NSpk    = [];     %Number of spikes ...
Cyc.MaxR    = [];     %Maximum synchronicity ... (SYNCCO)
Cyc.RaySig  = [];     %Rayleigh significance ... (RAYSIG)
Cyc.MaxPh   = [];     %Phase at maximum ... (PHASEMAX)
Cyc.MinPh   = [];     %Phase at minimum ... (PHASEMIN) NOT YET IMPLEMENTED
%Data from the most recent Inner Spiketime Interval (ISI) histogram ...
ISI.ReFrac  = [];     %Refractory period in ms ... (REFRAC)
%No data extracted from a First Spiketime Latency histogram ...                      
%Data from the most recent AutoCorrelogram curve ...
SAC.DF      = [];     %Dominant Frequency in Hz ... (SACDF)
SAC.BW      = [];     %Bandwidth in Hz ... (SACBW)
SAC.PH      = [];     %Height of peak in requested units ... (SACPH)
SAC.HHW     = [];     %Halfheight width in ms ... (SACHHW)
%Data from the most recent CrossCorrelogram curve ...
XC.DF       = [];     %Dominant Frequency in Hz ... (XCDF)
XC.BW       = [];     %Bandwidth in Hz ... (XCBW)
XC.PH       = [];     %Height of peak in requested units ... (XCPH)
XC.HHW      = [];     %Halfheight width in ms ... (XCHHW)
%Data from the most recent DifCor curve ...
DIF.DF      = [];     %Dominant Frequency in Hz ... (DIFDF)
DIF.BW      = [];     %Bandwidth in Hz ... (DIFBW)
DIF.PH      = [];     %Height of peak in requested units ... (DIFPH)
DIF.HHW     = [];     %Halfheight width in ms ... (DIFHHW)
%Data from the most recent Vector Strength Magnitude curve ...
VSM.MaxR      = [];   %Maximum synchonicity ... (VSMMAX)
VSM.BestVal   = [];   %Best frequency in Hz ... (VSMBVAL)
VSM.CutOffR   = [];   %Cutoff synchronicity ... (VSMCO)
VSM.CutOffVal = [];   %Cutoff value ... (VSMCOVAL)
VSM.RaySign   = [];   %Rayleigh significance ... (VSMRAYSIG)
%Data from the most recent Sync Rate curve ...
SR.MaxSR      = [];   %Maximum SR ... 
SR.BestVal   = [];   %Best frequency in Hz ... 
SR.RaySign   = [];   %Rayleigh significance ...
%Data from the most recent Sync Rate curve ...
Ry.MaxRY      = [];   %Maximum Ry ...
Ry.BestVal   = [];   %Best frequency in Hz ... 
Ry.RaySign   = [];   %Rayleigh significance ...
%Data from the most recent Vector Strength Phase curve ...
VSP.CD        = [];   %Characteristic delay (ms) ... (VSPCD)
VSP.CP        = [];   %Characteristic phase (cycles) ... (VSPCP)
VSP.pLinReg   = [];   %Probability of linear regression ... NOT YET IMPLEMENTED
VSP.RaySign   = [];   %Rayleigh significance ... (VSPRAYSIG)
%Data from the most recent regularity analysis ...
RGL.CV        = [];   %Coefficient of variation (ISCV) ...
%Data from the most recent trial rate distribution ...
TRD.Avg       = [];   %Average rate ...
TRD.Std       = [];   %Standard deviation on rate ...

CalcData = CollectInStruct(XData, YData, Thr, Rate, Hist, PST, Cyc, ISI, SAC, XC, DIF, VSM, VSP, RGL, TRD);

%---------------------------------------------------------------------------
RAPStat = CollectInStruct(GenParam, CalcParam, CalcParam2, ComLineParam, PlotParam, Memory, CalcData);
%---------------------------------------------------------------------------