function examples = getexamples(this)
%GETEXAMPLES   Get the examples.

%   Author(s): R. Losada
%   Copyright 2005 The MathWorks, Inc.

examples = {{ ...
    'Design a multistage interpolation filter.', ...
    'f = fdesign.interpolator(10,''lowpass'',''Fp,Fst,Ap,Ast'',.1,.12,1,96); ',...
    'Hm = design(f,''multistage'');',...
    'info(Hm)'},...
    { ...
    'Design a multistage decimation filter, use halfbands if possible.', ...
    'f = fdesign.decimator(10,''lowpass'',''Fp,Fst,Ap,Ast'',.08,.12,1,96); ',...
    'Hm = design(f,''multistage'',''usehalfbands'',true);',...
    'info(Hm)'},...
     { ...
    'Repeat previous design using an IIR linear phase halfband.', ...
    'f = fdesign.decimator(10,''lowpass'',''Fp,Fst,Ap,Ast'',.08,.12,1,96); ',...
    'Hm = design(f,''multistage'',''usehalfbands'',true,''HalfbandDesignMethod'',''iirlinphase'');',...
    'info(Hm)'},...
    { ...
    'Design an efficient singlerate filter using decimators and interpolators.', ...
    'f = fdesign.lowpass(''Fp,Fst,Ap,Ast'',.1,.12,1,96); ',...
    'Hm = design(f,''multistage'');',...
    'info(Hm)'}};

% [EOF]
