function examples = getexamples(~)
%GETEXAMPLES Get the examples.

%   Copyright 2011 The MathWorks, Inc.

examples ={{...
  'Design a 30-th order highpass inverse sinc filter with a stopband',...
  '%           frequency of 0.25*pi rad/sample. Specify a stopband attenuation',...
  '%           of 45 dB, and a passband ripple of 1 dB.',...
  'd = fdesign.isinchp(''N,Fst,Ast,Ap'',30,0.25,45,1);',...
  'Hd = design(d,''equiripple'');',...
  'fvtool(Hd)'}};

% [EOF]
