function Sym = RGB2ColSym(RGB)
%RGB2COLSYM converts RGB vector to color symbol
%   Sym = RGB2COLSYM(RGB) converts the 3 element vector RGB to a color symbol returned
%   by the character string Sym. If the RGB vector cannot be converted the empty
%   character string is returned.

%B. Van de Sande 05-02-2004

if (nargin ~= 1), error('Wrong number of input arguments.'); end
if ~isnumeric(RGB) | ~isequal(size(RGB), [1 3]), error('First argument should be a 3 element rowvector.'); end

if isequal(RGB, [0 0 1]),     Sym = 'b'; %blue ...
elseif isequal(RGB, [0 1 0]), Sym = 'g'; %green ...
elseif isequal(RGB, [1 0 0]), Sym = 'r'; %red ...
elseif isequal(RGB, [0 1 1]), Sym = 'c'; %cyan ...
elseif isequal(RGB, [1 0 1]), Sym = 'm'; %magenta ...
elseif isequal(RGB, [1 1 0]), Sym = 'y'; %yellow ...
elseif isequal(RGB, [0 0 0]), Sym = 'k'; %black ...
else,                         Sym = ''; end    