function sp = CompleteNoiseSpectrum(Buf);

% CompleteNoiseSpectrum - completes CalibSpec noise spectrum of bandpass noise by padding zeros
% Buf is generated by initNoiseBuf. 

NnonZero = Buf.NnonZero; % number of non-zero pos/neg freq components
iLow = Buf.iLow; % index of first non-zero component
nchan = Buf.nchan; % number of channels
N = Buf.NsamT; % total number of spectral components
NheadZeroPos = iLow-1; % # zero-valued spectral points at low-freq side prepending pos freqs
NtrailZeroPos = N-NheadZeroPos-NnonZero; % # zero-valued components at high freq trailing pos freqs
NtrailZeroNeg = NheadZeroPos-1; % # zero-valued components at high freq trailing neg freqs
NheadZeroNeg = N-NtrailZeroNeg-NnonZero; % # zero-valued spectral points at low-freq side prepending neg freqs
if isempty(Buf.CalibSpecNeg), % positive freqs only
   sp = [zeros(NheadZeroPos, nchan); Buf.CalibSpecPos]; % don't need trailing zeros if we use N-point ifft
else,
   sp = [zeros(NheadZeroPos, nchan); Buf.CalibSpecPos; zeros(NtrailZeroPos, nchan)] ...
      + [zeros(NheadZeroNeg, nchan); Buf.CalibSpecNeg; zeros(NtrailZeroNeg, nchan)];
end







