for n=1:length(D1_ABcType)
    ['df ' D1_ABcType(n).ds1.filename]
    ['SYNC MAN']
    ['id ' D1_ABcType(n).ds1.seqid]
    %
    ['ou sp']
    ['gv v4 valmax']
    ['exp v4 "maxrate' num2str(n) '"']
    %
    ['set pkl srw 50 100']
    ['ou pkl']
    ['gv v5 xmax']
    ['rr x v5 v5']
    ['nl pkl']
    ['gv v6 yvar']
    ['exp v6 "pkl' num2str(n) '"']
    %
    ['rr def']
    ['aw 10 25']
    ['bw 0.1']
    ['v7 5']
    ['v8 v6+v7']
    ['aw v6 v8']
    ['nl sp']
    ['gv v1 xvar']
    ['gv v2 yvar']
    ['aw v8 25']
    ['nl sp']
    ['gv v3 yvar']
    ['v2 / v3']
    ['ou scp v1 v2']
    ['gv v9 xmax']
    ['rr x v9 v9']
    ['ou scp v1 v2']
    ['gv v10 yvar']
    ['exp v10 "PSratio' num2str(n) '"']
    %
    ['clo all']
end;
['return']