function examples = getexamples(~)
%GETEXAMPLES Get the examples.

%   Copyright 2011 The MathWorks, Inc.

examples = {{ ...
    'Design a bandpass Equiripple filter. Constrain the first stopband to have ',...
    '%           an attenuation of 40 dB.',...
    'h  = fdesign.bandpass(''N,Fst1,Fp1,Fp2,Fst2,C'',50,0.3,0.4,0.7,0.8);', ...
    'h.Stopband1Constrained = true;',...
    'h.Astop1 = 40;',...
    'Hd = design(h, ''equiripple'');', ...
    '% Weight the passband to reduce ripple wile decreasing the second stopband attenuation.',...
    'Hd(2) = design(h, ''equiripple'', ''Wpass'', 30);'....  
    '% Compare the two designs.', ...
    'fvtool(Hd)'}};

% [EOF]
