function examples = getexamples(this)
%GETEXAMPLES   Get the examples.

%   Copyright 2007 The MathWorks, Inc.


examples = {{ ...
    'Design a quasi linear phase halfband highpass IIR filter of 32nd order ',...
    '% and a transition width of 0.2.',...
    'N = 32; % Must be a multiple of 4',...
    'TW = 0.2;',...
    'd = fdesign.halfband(''Type'',''Highpass'',''N,TW'',N,TW);',...
    'Hd = design(d,''iirlinphase'');',...
    'fvtool(Hd)'}};

% [EOF]
