%CD vs CF1, CF2, DF1, DF2, and DF
structplot(CFcombiselectWithDFS,'$CF1$','$CD$',...
    CFcombiselectWithDFS,'$CF2$','$CD$',...
    CFcombiselectWithDFS,'$DF1$','$CD$',...
    CFcombiselectWithDFS,'$DF2$','$CD$',...
    CFcombiselectWithDFS,'$BF$','$CD$','markers', {'of','of','o','o','o'},'Colors', {'m','g','r','c','k'})