D1_ABcType_PHL=structfilter(D1_ABcType,'strcmp($PSTHtype$,''PHL'')');
D1_ABcType_PLN=structfilter(D1_ABcType,'strcmp($PSTHtype$,''PLN'')');
D1_ABcType_PL=structfilter(D1_ABcType,'strcmp($PSTHtype$,''PL'')');
D1_ABcType_C=structfilter(D1_ABcType,'strcmp($PSTHtype$,''C'')');
D1_ABcType_O=structfilter(D1_ABcType,'strcmp($PSTHtype$,''O'')');
D1_ABcType_Oi=structfilter(D1_ABcType,'strcmp($PSTHtype$,''Oi'')');
D1_ABcType_OL=structfilter(D1_ABcType,'strcmp($PSTHtype$,''OL'')');
D1_ABcType_Oc=structfilter(D1_ABcType,'strcmp($PSTHtype$,''Oc'')');
D1_ABcType_X=structfilter(D1_ABcType,'strcmp($PSTHtype$,''X'')');
D1_ABcType_HITH=structfilter(D1_ABcType,'strcmp($PSTHtype$,''HITH'')');

structplot(D1_ABcType_PHL,'CF','THR',...
    D1_ABcType_PLN,'CF','THR',...
    D1_ABcType_PL,'CF','THR',...
    D1_ABcType_C,'CF','THR',...
    D1_ABcType_O,'CF','THR',...
    D1_ABcType_Oi,'CF','THR',...
    D1_ABcType_OL,'CF','THR',...
    D1_ABcType_Oc,'CF','THR',...
    D1_ABcType_X,'CF','THR',...
    'markers',{'+','^','o','*','s','s','s','s','x'}, 'Colors',{'k','k','k','k','k','b','g','r','k'})

