function c = hdldspblks_control

% Copyright 2009-2013 The MathWorks, Inc.

c = hdlnewcontrol(mfilename);

%%%%%%%%%%%%%%%%%%%%%%%%%%
%                        %
%SP BLOCKSET BINDINGS    %
%                        %
%%%%%%%%%%%%%%%%%%%%%%%%%%

% Signal Operations
c.defaultFor( ...
  'dspsigops/Repeat', {}, ...
  'hdldspblks.Repeat');

c.defaultFor( ...
  'dspsigops/NCO', {}, ...
  'hdldspblks.NCO');

c.defaultFor( ...
  'dspsigops/Delay', {}, ...
  'hdldspblks.DSPDelay');

c.defaultFor( ...
  'dspsigops/Upsample', {}, ...
  'hdldspblks.Upsample');

c.defaultFor( ...
  'dspsigops/Downsample', {}, ...
  'hdldspblks.Downsample');


% Sources
c.defaultFor( ...
  'dspsrcs4/Sine Wave', {}, ...
  'hdldspblks.SineWave');


% Signal Management/Indexing
c.defaultFor( ...
  'dspindex/Multiport Selector', {}, ...
  'hdldspblks.MultiportSelector');

% S-Function sdspperm2
c.defaultFor( ...
  'dspindex/Variable Selector', {}, ...
  'hdldspblks.VariableSelector');

% Hardware friendly blocks 
% dsp.HDLNCO
c.defaultFor( ...  
  'dspsigops/NCO HDL Optimized', {}, ...
  'hdldspblks.HDLNCO');

% dsp.HDLFFT
c.defaultFor( ...  
  'dspxfrm3/FFT HDL Optimized', {}, ...
  'hdldspblks.HDLFFT');

% dsp.HDLIFFT
c.defaultFor( ...  
  'dspxfrm3/IFFT HDL Optimized', {}, ...
  'hdldspblks.HDLIFFT');
