function [wdt, wdtPanes] = wiringText(h);

header = strvcat(...
      'PROGRAMMABLE DEVICES (see Test | XbusMap menu of S232 controller):',...
      '   PD1, SS1_1, SS1_2, PA4_1, PA4_2, ET1', ...
      ' ',...
      'NON-PROGRAMMABLE DEVICES (AF_n is n-th analog filter; SD is spike discriminator): ',...
      '   HB5/HB6, AF_1, AF_2, (optional AF_3, AF_4)',...
      '   notes:',...
      '    1. inputs of all analog filters are connected per channel',...
      '    2. AF1 to AF4 must have increasing cutoff frequencies',...
      '    3. Also check SystemParameters menu of SGSRmainWindow',...
      ' ',...   
      'CONNECTIONS:');
% the curse of proportional fonts...
conn1 = strvcat(...
      'PD1[DAC0]',...
      'SS1_2[7]',...
      ' ',...
      'SS1_2[1]',...
      'SS1_2[3]',...
      'SS1_2[8]',...
      ' ',...
      'SS1_1[A]',...
      'SS1_1[1]',...
      'SS1_1[2]',...
      'SS1_1[3]',...
      'SS1_1[4]',...
      ' ',...
      'PA4_1[out]'...
      );
conn2 = strvcat(...
      ' <--> SS1_2[A]',...
      ' <--> SS1_2[C]',...
      ' ',...
      ' <--> AF_1..4[left-in]',...
      ' <--> AF_1..4[right-in]',...
      ' <--> SD(TTL-out)',...
      ' ',...
      ' <--> PA4_1[in]',...
      ' <--> AF_1[left-out]',...
      ' <--> AF_2[left-out]',...
      ' <--> AF_3[left-out]',...
      ' <--> AF_4[left-out]',...
      ' ',...
      ' <--> HBx[left-in]'...
      );
conn3 = strvcat(...
      ' PD1[DAC1]',...
      ' ET1[in-1]',...
      ' ',...
      ' SS1_2[2]',...
      ' SS1_2[4]',...
      ' ',...
      ' ',...
      ' SS1_1[C]',...
      ' SS1_1[5]',...
      ' SS1_1[6]',...
      ' SS1_1[7]',...
      ' SS1_1[8]',...
      ' ',...
      ' PA4_2[out]'...
      );
conn4 = strvcat(...
      ' <--> SS1_2[B]   ',...
      ' <--> SS1_2[D]',...
      ' ',...
      ' <--> SS1_2[6]',...
      ' <--> SS1_2[5]',...
      ' ',...
      ' ',...
      ' <--> PA4_2[in]',...
      ' <--> AF_1[right-out]',...
      ' <--> AF_2[right-out]',...
      ' <--> AF_3[right-out]',...
      ' <--> AF_4[right-out]',...
      ' ',...
      ' <--> HBx[right-in]'...
      );
conn = [conn1 conn2 conn3 conn4];
wdt = strvcat(header, conn);
if nargout>1,
   wdtPanes.header = header;
   wdtPanes.conn1 = conn1;
   wdtPanes.conn2 = conn2;
   wdtPanes.conn3 = conn3;
   wdtPanes.conn4 = conn4;
end

   if nargin>0,
      set(h,'string', wdt)
   end
   
