function examples = getexamples(this) %#ok<INUSD>
%GETEXAMPLES   Get the examples.

%   Copyright 2009 The MathWorks, Inc.

examples = {{ ...
    '% Design a ITU-R 468-4 compliant IIR weighting filter for a sampling ',...
    '%frequency of 48 KHz. Return the filter with a default df2sos structure.',...
    'd = fdesign.audioweighting(''WT'', ''ITUR4684'',48e3);',...
    'Hd = design(d,''iirlpnorm'');',...
    'fvtool(Hd)'}};

% [EOF]
