function fig = empty_fig()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load empty_fig

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','D:\SGSRdevelop\SGSR\vs12\STIMMENU\CONSTRUCTION\empty.fig', ...
	'MenuBar','none', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[150 108 523 422], ...
	'Tag','Fig1', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[89.5 205 34.5 12.75], ...
	'String','filename:', ...
	'Style','text', ...
	'Tag','FilenamePrompt', ...
	'TooltipString',mat1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[127.75 204.5 75 15], ...
	'String','RedProbe', ...
	'Style','edit', ...
	'Tag','FilenameEdit');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','PRL;', ...
	'ListboxTop',0, ...
	'Position',[211.75 204.5 40 15], ...
	'String','Browse..', ...
	'Tag','FilenameButton');
if nargout > 0, fig = h0; end
