function Props = GetMenuProps(figh);

if nargin<1, figh=gcf; end;

% collect all properties of figure in struct
Props = get(figh);
% list & remove invalid, undesired, and irrelevant fields
ToRemove = {...
      'Children', ...
      'CurrentAxes', ...
      'CurrentCharacter', ...
      'CurrentObject', ...
      'CurrentPoint', ...
      'FixedColors', ...
      'HandleVisibility', ...
      'IntegerHandle', ...
      'PaperOrientation', ...
      'PaperPosition', ...
      'PaperPositionMode', ...
      'PaperSize', ...
      'PaperType', ...
      'PaperUnits', ...
      'Parent', ...
      'Selected', ...
      'SelectionType', ...
      'Visible', ...};
      'Type'};
for ii=1:length(ToRemove),
   Props = rmfield(Props, ToRemove{ii});
end
