function E = nernst(Tc, z, Cout, Cin)
%NERNST calculate equilibrium potential for ion according to the Nernst-equation

%B. Van de Sande 18-08-2003

R = 8.314;       %Universal gas constant in J/(mol*K) ...
F = 96485;       %Faraday constant in C ...
T = Tc + 273.15; %Temperature in Kelvin ...

E = (R*T)/(z*F) * log(Cout/Cin); %Concentrations given in mol/l or M ...