function examples = getexamples(this)
%GETEXAMPLES Get the examples.

%   Copyright 2007 The MathWorks, Inc.

examples = {{ ...
    'Design a 90th order halfband lowpass Kaiser windowed filter with at least ', ...
    '% 60 dB of stopband attenuation.',...
    'N = 90; % Filter Order', ...
    'Ast = 60; % Stopband Attenuation (dB)', ...
    'h  = fdesign.halfband(''Type'',''Lowpass'',''N,Ast'',N,Ast);', ...
    'Hd = design(h,''kaiserwin'');', ...
    'fvtool(Hd)'}};

