fields = {'id', 'side', 'cf','cutting','section','zsc','kind','tree','temination','branch_order','distance',...
    'pre_x','x','y','z','noncorrected_z','sectiontop_z','dp_x','dp_y','dp_z','noncorrected_dp_z',...
    'vp_x','vp_y','vp_z','noncorrected_vp_z','ep_minus_vp','dp_minus_vp','ep_minus_vp_on_dp_minus_vp',...
    'fb_distance','fb_x','fb_y','fb_z','rp_x','rp_y','rp_z','cp_x','cp_y','cp_z',...
    'square_ep_minus_rp','ep_minus_rp','ep_minus_rp_on_cp_minus_rp',...
    'al_from_ml','al_from_fb','group','gp','gp_distance','gp_x','gp_y','gp_z'};
contra_data = cell2struct(celldata(2:280,:), fields, 2);





