%for n=1:length(D1_ABcType)
    rapcmd(['df ' D(1).ds1.filename])
    rapcmd('SYNC MAN')
    rapcmd(['id ' D(1).ds1.seqid])
    %
    rapcmd('ou sp')
    rapcmd('gv v4 valmax')
    rapcmd(['exp v4 "maxrate' num2str(1) '"'])
    %
    rapcmd('set pkl srw 50 100')
    rapcmd('ou pkl')
    rapcmd('gv v5 xmax')
    rapcmd('rr x v5 v5')
    rapcmd('nl pkl')
    rapcmd('gv v6 yvar')
    rapcmd(['exp v6 "pkl' num2str(1) '"'])
    %
    rapcmd('rr def')
    rapcmd('aw 10 25')
    rapcmd('bw 0.1')
    rapcmd('v7 5')
    rapcmd('v8 v6+v7')
    rapcmd('aw v6 v8')
    rapcmd('nl sp')
    rapcmd('gv v1 xvar')
    rapcmd('gv v2 yvar')
    rapcmd('aw v8 25')
    rapcmd('nl sp')
    rapcmd('gv v3 yvar')
    rapcmd('v2 / v3')
    rapcmd('ou scp v1 v2')
    rapcmd('gv v9 xmax')
    rapcmd('rr x v9 v9')
    rapcmd('ou scp v1 v2')
    rapcmd('gv v10 yvar')
    rapcmd(['exp v10 "PSratio' num2str(1) '"'])
    %
    rapcmd('clo all')
%end;
rapcmd('return')