
%contra
for n=1:length(contra_data)
    contra_data(n).ds1.filename = [contra_data(n).id ' ' contra_data(n).side];
    contra_data(n).ds1.icell = n;%[contra_data(n).id ' ' contra_data(n).side];
end;

contra_data_89021_22=contra_data(1:6);
contra_data_87039_10=contra_data(7:82);
contra_data_87102_7=contra_data(83:110);
contra_data_89007_39=contra_data(111:116);
contra_data_87039_9=contra_data(117:140);
contra_data_89141_27=contra_data(141:161);
contra_data_88107_15=contra_data(162:175);
contra_data_87091_27=contra_data(176:184);
contra_data_89151_16=contra_data(185:279);



structplot(contra_data_89021_22,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_87039_10,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_87102_7,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_89007_39,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_87039_9,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_89141_27,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_88107_15,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_87091_27,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_89151_16,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    'xlim',[0 1],'ylim',[0 1]);hold on;


for n=1:length(guinan)
    if strcmp(guinan(n).side,'contra')==1
    plot(guinan(n).ep_minus_rp_on_cp_minus_rp,guinan(n).ep_minus_vp_on_dp_minus_vp,'k*','markersize',12);hold on;
    end;
end;
hold off;

%for contra figure
structplot(contra_data_89021_22,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_87039_10,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_87102_7,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_89007_39,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_87039_9,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_89141_27,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_88107_15,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_87091_27,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    contra_data_89151_16,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    'xlim',[0 1],'ylim',[0 1],...
    'info','no','markers',{'^w','vf','^w','vf','^w','vf','^w','vf'},...
    'colors',{'k', 'k', 'r', 'r', 'b', 'b', 'g', 'g', 'c'});hold on;

for n=1:length(guinan)
    if strcmp(guinan(n).side,'contra')==1
    plot(guinan(n).ep_minus_rp_on_cp_minus_rp,guinan(n).ep_minus_vp_on_dp_minus_vp,'k*','markersize',12);hold on;
    end;
end;
hold off;

%ipsi
for n=1:length(ipsi_data)
    ipsi_data(n).ds1.filename = [ipsi_data(n).id ' ' ipsi_data(n).side];
    ipsi_data(n).ds1.icell = n;%[ipsi_data(n).id ' ' ipsi_data(n).side];
end;

ipsi_data_89021_22=ipsi_data(1:22);
ipsi_data_89007_39=ipsi_data(23:33);
ipsi_data_89007_43=ipsi_data(34:40);
ipsi_data_90043_15=ipsi_data(41:70);
ipsi_data_87056_24=ipsi_data(71:81);
ipsi_data_88311_20=ipsi_data(82:117);
ipsi_data_88011_3=ipsi_data(118:121);

structplot(ipsi_data_89021_22,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    ipsi_data_89007_39,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    ipsi_data_89007_43,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    ipsi_data_90043_15,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    ipsi_data_87056_24,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    ipsi_data_88311_20,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    ipsi_data_88011_3,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    'xlim',[0 1],'ylim',[0 1]);hold on;

for n=1:length(guinan)
    if strcmp(guinan(n).side,'ipsi')==1
    plot(guinan(n).ep_minus_rp_on_cp_minus_rp,guinan(n).ep_minus_vp_on_dp_minus_vp,'k*','markersize',12);hold on;
    end;
end;
hold off;

%for ipsi figure
structplot(ipsi_data_89021_22,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    ipsi_data_89007_39,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    ipsi_data_89007_43,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    ipsi_data_90043_15,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    ipsi_data_87056_24,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    ipsi_data_88311_20,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    ipsi_data_88011_3,'ep_minus_rp_on_cp_minus_rp','ep_minus_vp_on_dp_minus_vp',...
    'xlim',[0 1],'ylim',[0 1],...
    'info','no','markers',{'^w','vf','^w','vf','^w','vf'},...
    'colors',{'k', 'k', 'r', 'r', 'b', 'g', 'g'});hold on;

for n=1:length(guinan)
    if strcmp(guinan(n).side,'ipsi')==1
    plot(guinan(n).ep_minus_rp_on_cp_minus_rp,guinan(n).ep_minus_vp_on_dp_minus_vp,'k*','markersize',12);hold on;
    end;
end;
hold off;

