function thiscopy(this, Hd)
%THISCOPY   Copy the properties defined at this level.

%   Author(s): J. Schickler
%   Copyright 1999-2004 The MathWorks, Inc.

set(this, 'privoutwl', get(Hd, 'privoutwl'), ...
    'privoutfl', get(Hd, 'privoutfl'), ...
    'FilterInternals', Hd.FilterInternals, ...
    'privFilterInternals', Hd.privFilterInternals, ...
    'privstatewl', Hd.privstatewl, ...
    'privstatefl',  Hd.privstatefl, ...
    'PolyAccfimath', Hd.PolyAccfimath);

if strcmpi(Hd.FilterInternals,'SpecifyPrecision'),
    set(this, 'AccumWordLength', get(Hd, 'AccumWordLength'), ...
        'AccumFracLength', get(Hd, 'AccumFracLength'),...
        'RoundMode', get(Hd, 'RoundMode'),...
        'OverflowMode', get(Hd, 'OverflowMode'));
end

% [EOF]
