%SNMODELMEX    shot-noise coincidence model (MEX).
%   SpkOut = SNMODELMEX(P, Spk1, Spk2, ..., SpkN) calculates an
%   output spiketrain generated by a shot-noise coincidence
%   model. The parameters of the model are set via a scalar
%   structure P and are:
%       P.ninputs : number of inputs.
%       P.ainputs : amplitude of the inputs givan as a rowvector
%                   with the same length as the number of inputs.
%       P.trefrac : refractory period in ms.
%       P.tdecay  : decay period of input amplitude in ms.
%       P.thr     : threshold level.
%   The actual spiketrain inputs for the model must be given
%   as numerical rowvectors. The model is implemented as a MEX
%   function for optimal performance.

%B. Van de Sande 12-08-2004