function examples = getexamples(this) %#ok<INUSD>
%GETEXAMPLES   Get the examples.

%   Copyright 2009 The MathWorks, Inc.

examples = {{ ...
    '% Design a class 2, A-weighting filter compliant with the ',...
    '% ANSI S1.42-2001 standard for a sampling frequency of 44.1 KHz. ',...
    '% Return the filter with a default df2sos structure.',...
    'WeightingType = ''A'';',...
    'Class = 2;',...
    'd = fdesign.audioweighting(''WT,Class'',''A'',2,44.1e3);',...
    'Hd = design(d,''ansis142'');',...
    'fvtool(Hd)'}
    {
    '% Design a class 1, C-weighting filter compliant with the ',...
    '% ANSI S1.42-2001 standard for a sampling frequency of 48 KHz. ',...
    '% Set the SOS scaling to ''Linf'' and return the filter with a df1sos ',...
    '% structure.',...
    'd = fdesign.audioweighting(''WT,Class'',''C'',1,48e3);',...
    'Hd = design(d,''ansis142'',''SOSScaleNorm'',''Linf'',''FilterStructure'',''df1sos'');',...
    'fvtool(Hd)'}};

% [EOF]
